# PR Auto-Label Configuration
# Labels are applied based on changed files

# Agent-related changes
agent:
  - crates/octo-ai/**
  - crates/octo-runtime/**
  - crates/agents/**

# Protocol/network layer
protocol:
  - crates/octo-network/**
  - crates/octo-p2p/**
  - crates/blockchain/**

# Runtime/execution
runtime:
  - crates/octo-runtime/**
  - crates/octo-sandbox/**
  - crates/executor/**

# Core infrastructure
core:
  - crates/octo-core/**
  - crates/octo-registry/**
  - crates/octo-identity/**

# CLI tools
cli:
  - crates/octo-cli/**
  - crates/repl/**

# Documentation
docs:
  - docs/**
  - **/*.md
  - .github/**/*.md

# CI/CD
ci:
  - .github/workflows/**
  - .github/actions/**

# Smart contracts
contracts:
  - contracts/**

# Developer tooling
tooling:
  - scripts/**
  - tools/**
  - dev/**

# AI/ML
ai:
  - crates/ai/**
  - crates/inference/**
  - crates/ml/**

# Security
security:
  - crates/crypto/**
  - crates/security/**

# Testing
testing:
  - tests/**
  - **/*_test.rs
  - **/tests/**

# Dependencies
dependencies:
  - Cargo.toml
  - Cargo.lock
  - package.json
  - requirements.txt
  - **/Cargo.toml
