# PR Auto-Label Configuration
# Labels are applied based on changed files

# Agent-related changes
agent:
  - changed_files:
    - crates/octo-ai/**
    - crates/octo-runtime/**
    - crates/agents/**

# Protocol/network layer
protocol:
  - changed_files:
    - crates/octo-network/**
    - crates/octo-p2p/**
    - crates/blockchain/**

# Runtime/execution
runtime:
  - changed_files:
    - crates/octo-runtime/**
    - crates/octo-sandbox/**
    - crates/executor/**

# Core infrastructure
core:
  - changed_files:
    - crates/octo-core/**
    - crates/octo-registry/**
    - crates/octo-identity/**

# CLI tools
cli:
  - changed_files:
    - crates/octo-cli/**
    - crates/repl/**

# Documentation
docs:
  - changed_files:
    - docs/**
    - "**/*.md"
    - .github/**/*.md

# CI/CD
ci:
  - changed_files:
    - .github/workflows/**
    - .github/actions/**

# Smart contracts
contracts:
  - changed_files:
    - contracts/**

# Developer tooling
tooling:
  - changed_files:
    - scripts/**
    - tools/**
    - dev/**

# AI/ML
ai:
  - changed_files:
    - crates/ai/**
    - crates/inference/**
    - crates/ml/**

# Security
security:
  - changed_files:
    - crates/crypto/**
    - crates/security/**

# Testing
testing:
  - changed_files:
    - tests/**
    - "**/*_test.rs"
    - "**/tests/**"

# Dependencies
dependencies:
  - changed_files:
    - Cargo.toml
    - Cargo.lock
    - package.json
    - requirements.txt
    - "**/Cargo.toml"
