//! Matrix adapter for DOT using matrix-rust-sdk (RFC-0850 S8.1, PlatformType::Matrix)
//!
//! This adapter replaces the in-house reqwest-based Matrix adapter with the
//! official matrix-rust-sdk for better federation support, media handling,
//! and long-term maintenance.
//!
//! Exports C ABI functions (`adapter_version`, `platform_type`, `create_adapter`,
//! `destroy_adapter`) for dynamic loading as a cdylib plugin.
//!
//! Matrix is the most aligned platform for CipherOcto — it is itself federated
//! and decentralized, matching CipherOcto's architecture.
//!
//! ## Configuration
//!
//! ```json
//! {
//!   "homeserver_url": "https://matrix.example.com",
//!   "user_id": "@bot:matrix.example.com",
//!   "device_id": "MYDEVICEID",
//!   "access_token": "syt_xxx",
//!   "refresh_token": "syr_xxx",
//!   "rooms": ["!abcdef:example.com"]
//! }
//! ```
//!
//! The `user_id`, `device_id`, and `access_token` fields are required and
//! match the session material captured by `octo-matrix-onboard` (mission
//! 0850h-a). The optional `refresh_token` is populated when the homeserver
//! issues one; the adapter uses it to refresh `access_token` in-memory on
//! 401. Configs produced before mission 0850h-a (which had only
//! `homeserver_url`/`access_token`/`rooms`) MUST be re-generated by running
//! `octo-matrix-onboard login` — old configs will fail to deserialize.

use base64::Engine;
use matrix_sdk::Client;
use serde::Deserialize;
use std::path::PathBuf;

pub mod config_writer;
pub mod session_loader;

fn redact_token(token: &str) -> String {
    if token.len() > 8 {
        format!("{}***", &token[..8])
    } else {
        "***".to_string()
    }
}

/// Errors that `MatrixAdapter::new` can surface. R1-L14: the previous
/// shape (`Result<Self, String>`) forced the C ABI at line 622-635 to
/// discard the error string. This structured type lets cdylib hosts
/// read a stable error category via `last_error()`.
#[derive(Debug, thiserror::Error)]
pub enum MatrixAdapterError {
    #[error("session load: {0}")]
    SessionLoad(String),
    #[error("invalid user_id '{user_id}': {source}")]
    InvalidUserId {
        user_id: String,
        source: matrix_sdk::ruma::IdParseError,
    },
    #[error("failed to create tokio runtime: {0}")]
    Runtime(String),
    #[error("client build: {0}")]
    ClientBuild(String),
    #[error("session restore: {0}")]
    SessionRestore(String),
}

/// Matrix adapter configuration.
///
/// The required `user_id` / `device_id` / `access_token` fields are
/// captured by `octo-matrix-onboard` (mission 0850h-a). The optional
/// `refresh_token` is populated when the homeserver issues one.
///
/// `passphrase` (mission 0850h-b) is an optional field that, when
/// `Some`, is mixed into the SDK's crypto-store key derivation so the
/// on-disk Olm/Megolm session material is encrypted at rest. When
/// `None`, the SDK falls back to the platform default (system keyring
/// on supported platforms, in-memory otherwise). It is never serialized
/// back to disk — the operator supplies it on the CLI as
/// `--passphrase-stdin` and the adapter holds it in memory only.
///
/// `config_path` / `force_writeback` (mission 0850h-c) control the
/// on-disk writeback of rotated `access_token` / `refresh_token`
/// pairs: when `config_path` is non-empty, the adapter writes the
/// rotated pair back to it (atomic rename + flock) so long-running
/// daemons survive a process restart without re-onboarding. When
/// `config_path` is empty, writeback is disabled (in-memory or
/// read-only deployments). `force_writeback` skips the
/// before-snapshot check that protects against two long-running
/// processes clobbering each other's token rotations.
#[derive(Clone, Deserialize, serde::Serialize)]
pub struct MatrixConfig {
    /// Matrix homeserver URL
    pub homeserver_url: String,
    /// Authenticated user (e.g. `@bot:matrix.example.com`).
    /// Required by `restore_session` — must match `access_token`.
    pub user_id: String,
    /// Device ID (e.g. `ABCDEFGHIJ`). Required by `restore_session`.
    pub device_id: String,
    /// Access token for authentication (long-lived or
    /// refresh-rotated). Never serialized back to disk; the on-disk
    /// rotation path is mission 0850h-c.
    #[serde(skip_serializing)]
    pub access_token: String,
    /// Optional refresh token issued by the homeserver. When
    /// present, the adapter calls `oauth.refresh_token(...)` on 401
    /// and holds the rotated pair in memory. None when the
    /// homeserver doesn't issue refresh tokens (some password
    /// flows).
    #[serde(default, skip_serializing_if = "Option::is_none", skip_serializing)]
    pub refresh_token: Option<String>,
    /// Optional passphrase for the SDK's crypto store. When `Some`,
    /// the SDK derives an encryption key from it for the on-disk
    /// Olm/Megolm session material (mission 0850h-b). When `None`, the
    /// SDK uses the platform default. Never serialized back to disk
    /// — supplied on the CLI as `--passphrase-stdin`.
    #[serde(default, skip_serializing_if = "Option::is_none", skip_serializing)]
    pub passphrase: Option<String>,
    /// On-disk location of the config file. When the SDK rotates the
    /// access/refresh-token pair on a 401 response, the adapter writes
    /// the rotated pair back to this path (mission 0850h-c). When
    /// `PathBuf::new()` (the default), writeback is disabled — useful
    /// for in-memory or read-only deployments.
    #[serde(default)]
    pub config_path: PathBuf,
    /// Skip the before-snapshot check on writeback (mission 0850h-c).
    /// The default `false` protects against two long-running processes
    /// silently clobbering each other's token rotations; set to `true`
    /// from the host process when only one writer is expected.
    #[serde(default)]
    pub force_writeback: bool,
    /// When `true` (the default), the adapter loads the session from
    /// the multi-account stoolap store when `session_store_path` is
    /// non-empty. When `false`, the adapter reads the legacy
    /// single-file config at `config_path` (mission 0850h-a / 0850h-c
    /// behavior; useful for backward compatibility with deployments
    /// that pre-date the store).
    #[serde(default = "default_true")]
    pub use_session_store: bool,
    /// On-disk location of the multi-account stoolap store (mission
    /// 0850h-d). When `PathBuf::new()`, the store path defaults to
    /// the per-platform `ProjectDirs("com", "cipherocto", "cipherocto")
    /// / data_dir() / sessions.db` location. Ignored when
    /// `use_session_store` is `false`.
    #[serde(default)]
    pub session_store_path: PathBuf,
    /// Room IDs to monitor
    pub rooms: Vec<String>,
}

fn default_true() -> bool {
    true
}

impl std::fmt::Debug for MatrixConfig {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("MatrixConfig")
            .field("homeserver_url", &self.homeserver_url)
            .field("user_id", &self.user_id)
            .field("device_id", &self.device_id)
            .field("access_token", &redact_token(&self.access_token))
            .field(
                "refresh_token",
                &self.refresh_token.as_deref().map(redact_token),
            )
            .field(
                "passphrase",
                &self.passphrase.as_deref().map(|_| "***".to_string()),
            )
            .field("rooms", &self.rooms)
            .finish()
    }
}

/// Matrix adapter using matrix-rust-sdk.
pub struct MatrixAdapter {
    config: MatrixConfig,
    client: Client,
    #[allow(dead_code)] // Used during construction; kept for cdylib lifecycle
    runtime: tokio::runtime::Runtime,
    /// Sync token for incremental /sync (ZeroClaw pattern).
    next_batch: std::sync::Mutex<Option<String>>,
    /// Cached bot user ID (e.g., @bot:server)
    user_id: std::sync::Mutex<Option<String>>,
}

impl MatrixAdapter {
    /// Create a new Matrix adapter from config.
    ///
    /// Builds a tokio runtime, initializes the matrix-sdk Client, and
    /// restores the session from the config. The actual session
    /// material (access / refresh tokens) is resolved by
    /// `session_loader::load`, which honors the new mission 0850h-d
    /// `use_session_store` field:
    ///
    /// - `use_session_store = true` (the default): load the row from
    ///   the multi-account stoolap store at `session_store_path` (or
    ///   the per-platform default).
    /// - `use_session_store = false` AND `config_path` is set: read
    ///   the legacy 0850h-a / 0850h-c JSON file.
    /// - `use_session_store = false` AND `config_path` is empty: use
    ///   the config's in-memory `access_token` / `refresh_token`
    ///   fields directly (cdylib hosts that build a MatrixConfig from
    ///   a config blob without persisting it).
    ///
    /// On 401 the adapter calls the SDK's `refresh_access_token` (when
    /// `refresh_token` is `Some`) and holds the rotated pair in memory;
    /// on-disk rotation is mission 0850h-c. The host process drives
    /// the actual writeback via `persist_session_to_disk()`.
    pub fn new(config: MatrixConfig) -> Result<Self, MatrixAdapterError> {
        use matrix_sdk::authentication::matrix::MatrixSession;
        use matrix_sdk::ruma::{OwnedDeviceId, OwnedUserId};
        use matrix_sdk::{SessionMeta, SessionTokens};

        let runtime = tokio::runtime::Builder::new_multi_thread()
            .enable_all()
            .build()
            .map_err(|e| MatrixAdapterError::Runtime(e.to_string()))?;

        // Mission 0850h-d: resolve the actual session material via
        // the loader. The returned `LoadedSession` overrides the
        // config's `access_token` / `refresh_token` for the SDK
        // restore call (the original config is kept on `self.config`
        // for writeback / display purposes). R1-M23: `load` is
        // `async`; we drive it on the multi_thread runtime this
        // function just built (the loader no longer builds a
        // per-call `current_thread` runtime internally).
        let loaded = runtime
            .block_on(session_loader::load(&config))
            .map_err(|e| MatrixAdapterError::SessionLoad(e.to_string()))?;

        let user_id = OwnedUserId::try_from(loaded.user_id.as_str()).map_err(
            |e: matrix_sdk::ruma::IdParseError| MatrixAdapterError::InvalidUserId {
                user_id: loaded.user_id.clone(),
                source: e,
            },
        )?;
        let device_id = OwnedDeviceId::from(loaded.device_id.as_str());

        let session = MatrixSession {
            meta: SessionMeta { user_id, device_id },
            tokens: SessionTokens {
                access_token: loaded.access_token,
                refresh_token: loaded.refresh_token,
            },
        };

        // Mission 0850h-b: wire the SDK's `sqlite_store` with the
        // operator-supplied `passphrase` so the on-disk Olm/Megolm
        // material is encrypted at rest. R1-H8 fixed the prior
        // "passphrase is held in memory, host process will pass to
        // `.sqlite_store` directly" doc-claim that was
        // never realised in code.
        //
        // The store path is derived from `config_path`:
        // `<dir>/<basename>.store.sqlite`. The store is opened
        // ONLY when the operator supplied a passphrase — without a
        // passphrase, the SDK's default in-memory crypto store is
        // good enough for the process lifetime and avoids the
        // matrix-sdk 0.17.0 migration `near "DROP": syntax error`
        // bug that surfaces on a fresh DB. (Future work: file an
        // upstream issue or gate the migration behind a feature.)
        let store_path =
            if config.passphrase.is_some() && !config.config_path.as_os_str().is_empty() {
                let mut p = config.config_path.clone();
                let stem = p
                    .file_stem()
                    .map(|s| s.to_os_string())
                    .unwrap_or_else(|| std::ffi::OsString::from("matrix"));
                p.set_file_name(stem);
                p.set_extension("store.sqlite");
                Some(p)
            } else {
                None
            };

        let homeserver_url = loaded.homeserver_url.clone();
        let passphrase_ref = config.passphrase.as_deref();
        let client = runtime.block_on(async {
            let mut builder = Client::builder()
                .homeserver_url(&homeserver_url)
                // Enable in-memory refresh on 401 when a refresh_token is
                // present. The SDK rotates tokens internally; the on-disk
                // config is left untouched (mission 0850h-c writes back).
                .handle_refresh_tokens();
            // Wire the on-disk crypto store ONLY when a passphrase
            // is set (mission 0850h-b). The SDK's default in-memory
            // store handles the no-passphrase case for the lifetime
            // of the process.
            if let Some(path) = store_path {
                if let Some(parent) = path.parent() {
                    let _ = std::fs::create_dir_all(parent);
                }
                builder = builder.sqlite_store(&path, passphrase_ref);
            }
            let c = builder
                .build()
                .await
                .map_err(|e| MatrixAdapterError::ClientBuild(e.to_string()))?;
            c.restore_session(session)
                .await
                .map_err(|e| MatrixAdapterError::SessionRestore(e.to_string()))?;
            Ok::<_, MatrixAdapterError>(c)
        })?;

        // Cache the bot user_id for self_handle()
        let cached_user = std::sync::Mutex::new(Some(loaded.user_id));

        Ok(Self {
            config,
            client,
            runtime,
            next_batch: std::sync::Mutex::new(None),
            user_id: cached_user,
        })
    }

    /// Create from JSON config bytes (used by plugin ABI).
    pub fn from_config_bytes(config: &[u8]) -> Result<Self, MatrixAdapterError> {
        let config: MatrixConfig = serde_json::from_slice(config)
            .map_err(|e| MatrixAdapterError::SessionLoad(format!("Invalid config: {}", e)))?;
        Self::new(config)
    }

    /// Persist the current session to the on-disk config file.
    ///
    /// R1-H1: this is the wired writeback the mission 0850h-c
    /// acceptance criterion required. Host processes call this after
    /// observing a 401 + refresh cycle (e.g., by polling
    /// `client.session_tokens()` or by hooking the SDK's
    /// `SessionChange` event). The function:
    ///
    /// 1. Captures the **current** access/refresh token from the SDK.
    /// 2. Updates `self.config` with the rotated pair.
    /// 3. Calls `config_writer::writeback` against the snapshot
    ///    captured at adapter construction (or, if `force_writeback`
    ///    is set, against the on-disk file as-is).
    /// 4. Surfaces `WritebackError::LockHeld` as a non-fatal warning
    ///    (the host can retry) and `SnapshotMismatch` as a fatal
    ///    "two writers, refusing to clobber" error unless
    ///    `force_writeback` is set.
    ///
    /// When `config_path` is empty, this is a no-op (in-memory or
    /// read-only deployment).
    pub fn persist_session_to_disk(
        &self,
    ) -> Result<config_writer::WritebackOutcome, MatrixAdapterError> {
        if self.config.config_path.as_os_str().is_empty() {
            return Ok(config_writer::WritebackOutcome { written: false });
        }
        let current = self.client.session_tokens().ok_or_else(|| {
            MatrixAdapterError::SessionLoad("client has no session tokens".to_string())
        })?;
        let rotated = {
            let mut cfg = self.config.clone();
            cfg.access_token = current.access_token.clone();
            cfg.refresh_token = current.refresh_token.clone();
            cfg
        };
        let on_disk_before = config_writer::OnDiskConfig::from_config(&self.config);
        match config_writer::writeback(
            &self.config.config_path,
            &on_disk_before,
            &rotated,
            self.config.force_writeback,
        ) {
            Ok(outcome) => Ok(outcome),
            Err(config_writer::WritebackError::LockHeld { .. }) => {
                tracing::warn!(
                    path = %self.config.config_path.display(),
                    "config writeback: lock held by another process; rotated pair stays in memory"
                );
                // Non-fatal: return success with `written: false` so
                // the host can retry on the next 401 cycle.
                Ok(config_writer::WritebackOutcome { written: false })
            }
            Err(config_writer::WritebackError::SnapshotMismatch) => Err(
                MatrixAdapterError::SessionLoad(
                    "config on-disk contents changed; refusing to overwrite (pass --force-writeback)"
                        .to_string(),
                ),
            ),
            Err(e) => Err(MatrixAdapterError::SessionLoad(format!(
                "writeback: {}",
                e
            ))),
        }
    }

    /// Run an async operation on the embedded tokio runtime.
    #[allow(dead_code)] // Available for cdylib hosts without their own runtime
    fn block_on<F: std::future::Future>(&self, future: F) -> F::Output {
        self.runtime.block_on(future)
    }

    /// Encode an envelope as base64 with DOT prefix.
    ///
    /// R1-L18: the base64 alphabet is `URL_SAFE_NO_PAD` per
    /// RFC-0850 §3.2 (the DOT wire format). All DOT adapters in
    /// the workspace MUST use the same alphabet for the
    /// encode → transport → decode round-trip to work. The
    /// constant lives here as the single source of truth; if a
    /// second adapter picks a different alphabet, `decode_envelope`
    /// will fail with a "Base64 decode error" on the receiver
    /// side, which is the intended loud-failure mode.
    pub fn encode_envelope(envelope_bytes: &[u8]) -> String {
        format!(
            "DOT/1/{}",
            base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(envelope_bytes)
        )
    }

    /// Decode a DOT-prefixed base64 envelope. See `encode_envelope`
    /// for the alphabet contract.
    pub fn decode_envelope(text: &str) -> Result<Vec<u8>, String> {
        let text = text.trim();
        let b64 = text
            .strip_prefix("DOT/1/")
            .ok_or_else(|| "Missing DOT/1/ prefix".to_string())?;
        base64::engine::general_purpose::URL_SAFE_NO_PAD
            .decode(b64)
            .map_err(|e| format!("Base64 decode error: {}", e))
    }

    /// Compute domain hash for a Matrix room ID.
    ///
    /// Hash input includes platform prefix per RFC-0850 §3.1:
    /// `BLAKE3-256("matrix:{room_id}")`
    ///
    /// R1-L15: trust model. The function does NOT validate that
    /// `room_id` is a well-formed Matrix room ID (`!opaque:server`).
    /// It lowercases the input and feeds it into BLAKE3-256,
    /// which gives a unique hash for every distinct input
    /// regardless of syntactic validity. Callers are trusted
    /// to pass a room ID the SDK can later resolve (a
    /// `MatrixConfig::rooms` value the host process intends
    /// to join). A malicious caller could in principle register
    /// a domain hash that collides with another platform's
    /// domain — but since the hash input includes the
    /// `matrix:` prefix per RFC-0850, cross-platform collision
    /// is impossible (BLAKE3 is a strong hash, so
    /// `BLAKE3("matrix:foo") != BLAKE3("ipfs:foo")` for all
    /// `foo`).
    pub fn domain_hash(room_id: &str) -> [u8; 32] {
        let normalized = room_id.trim().to_lowercase();
        *blake3::hash(format!("matrix:{}", normalized).as_bytes()).as_bytes()
    }

    /// Platform type constant (0x0003 = Matrix).
    pub const PLATFORM_TYPE: u16 = 0x0003;

    /// Maximum payload bytes per event (Matrix limit).
    pub fn max_payload_bytes() -> usize {
        65536
    }

    /// Rate limit: requests per second.
    pub fn rate_limit_per_second() -> u32 {
        100
    }
}

// --- PlatformAdapter trait implementation ---

use async_trait::async_trait;
use matrix_sdk::media::MediaFormat;
use matrix_sdk::ruma::{events::room::message::RoomMessageEventContent, RoomId};
use octo_network::dot::adapters::{
    backoff::RetryConfig, CapabilityReport, DeliveryReceipt, MediaCapabilities, PlatformAdapter,
    RawPlatformMessage,
};
use octo_network::dot::domain::{BroadcastDomainId, PlatformType};
use octo_network::dot::envelope::DeterministicEnvelope;
use octo_network::dot::error::PlatformAdapterError;

fn transport_err(msg: impl Into<String>) -> PlatformAdapterError {
    PlatformAdapterError::Unreachable {
        platform: "matrix".to_string(),
        reason: msg.into(),
    }
}

fn unix_epoch_now() -> u64 {
    use std::time::{SystemTime, UNIX_EPOCH};
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

#[async_trait]
impl PlatformAdapter for MatrixAdapter {
    async fn send_envelope(
        &self,
        domain: &BroadcastDomainId,
        envelope: &DeterministicEnvelope,
    ) -> Result<DeliveryReceipt, PlatformAdapterError> {
        let wire_bytes = envelope.to_wire_bytes();
        let encoded = Self::encode_envelope(&wire_bytes);

        // Find matching room by domain hash
        let room_id_str = self
            .config
            .rooms
            .iter()
            .find(|r| {
                let hash = Self::domain_hash(r);
                hash == domain.domain_hash
            })
            .ok_or_else(|| {
                transport_err(format!("No room found for domain {:?}", domain.domain_hash))
            })?;

        let room_id = RoomId::parse(room_id_str)
            .map_err(|e| transport_err(format!("Invalid room ID '{}': {}", room_id_str, e)))?;

        // R1-L16: race against the initial sync. `client.get_room`
        // returns `None` if the room is in `response.rooms.joined`
        // (the post-sync state) but has not yet been indexed by
        // the SDK's internal room map. The fix is to drive a
        // bounded initial sync (idempotent if sync already
        // completed) before looking up the room. We bound the
        // wait at 5s — the initial sync against a quiet
        // homeserver is typically <1s.
        if self.client.get_room(&room_id).is_none() {
            use matrix_sdk::config::SyncSettings;
            use std::time::Duration;
            let _ = self
                .client
                .sync_once(SyncSettings::default().timeout(Duration::from_secs(5)))
                .await
                .map_err(|e| transport_err(format!("initial sync before send: {}", e)))?;
        }

        let room = self.client.get_room(&room_id).ok_or_else(|| {
            transport_err(format!("Room {} not found in joined rooms", room_id_str))
        })?;

        // Retry with exponential backoff. R1-M20: the bound is
        // `0..max_retries` so the loop runs exactly `max_retries`
        // attempts (the +1 off-by-one silently turned the default
        // `max_retries: 3` into 4 attempts).
        let retry_cfg = RetryConfig::default();
        let mut last_err = String::new();

        for attempt in 0..retry_cfg.max_retries {
            let send_result = if wire_bytes.len() > Self::max_payload_bytes() {
                // Upload as media file for large envelopes
                let mime = "application/octet-stream"
                    .parse::<mime::Mime>()
                    .unwrap_or(mime::APPLICATION_OCTET_STREAM);
                match self
                    .client
                    .media()
                    .upload(&mime, wire_bytes.clone(), None)
                    .await
                {
                    Ok(response) => {
                        let content = RoomMessageEventContent::text_plain(format!(
                            "DOT/1/{}",
                            response.content_uri.as_str()
                        ));
                        room.send(content).await
                    }
                    Err(e) => {
                        let err_str = format!("{}", e);
                        last_err = err_str.clone();
                        if (err_str.contains("429")
                            || err_str.contains("rate limit")
                            || err_str.contains("M_LIMIT_EXCEEDED"))
                            && retry_cfg.should_retry(attempt)
                        {
                            let delay = retry_cfg.delay_for_attempt(attempt);
                            tokio::time::sleep(delay).await;
                            continue;
                        }
                        return Err(transport_err(err_str));
                    }
                }
            } else {
                let content = RoomMessageEventContent::text_plain(&encoded);
                room.send(content).await
            };

            match send_result {
                Ok(sent) => {
                    // R1-H5: bind the SDK's `event_id` from the
                    // `SentMessage` response into the delivery receipt
                    // so downstream code can correlate the receipt with
                    // the real Matrix event. The old code threw this
                    // away and synthesised a `Uuid::new_v4()` — that
                    // receipt could not be looked up on the
                    // homeserver, was non-deterministic across runs, and
                    // was invisible to receipts reconciliation.
                    let event_id = sent.response.event_id.to_string();
                    return Ok(DeliveryReceipt {
                        platform_message_id: event_id,
                        delivered_at: unix_epoch_now(),
                    });
                }
                Err(e) => {
                    let err_str = format!("{}", e);
                    last_err = err_str.clone();
                    if (err_str.contains("429")
                        || err_str.contains("rate limit")
                        || err_str.contains("M_LIMIT_EXCEEDED"))
                        && retry_cfg.should_retry(attempt)
                    {
                        let delay = retry_cfg.delay_for_attempt(attempt);
                        tokio::time::sleep(delay).await;
                        continue;
                    }
                    return Err(transport_err(err_str));
                }
            }
        }
        Err(transport_err(format!("Retries exhausted: {}", last_err)))
    }

    async fn receive_messages(
        &self,
        _domain: &BroadcastDomainId,
    ) -> Result<Vec<RawPlatformMessage>, PlatformAdapterError> {
        use matrix_sdk::config::SyncSettings;
        use std::time::Duration;

        let since = self.next_batch.lock().unwrap().clone();

        let mut sync_settings = SyncSettings::default().timeout(Duration::from_secs(5));
        if let Some(ref token) = since {
            sync_settings = sync_settings.token(token);
        }

        let response = self
            .client
            .sync_once(sync_settings)
            .await
            .map_err(|e| transport_err(format!("Sync failed: {}", e)))?;

        // Persist next_batch for next call
        if !response.next_batch.is_empty() {
            *self.next_batch.lock().unwrap() = Some(response.next_batch.clone());
        }

        let mut result = Vec::new();
        for (room_id, joined) in &response.rooms.joined {
            for event in &joined.timeline.events {
                // R1-L17: typed deserialization. We attempt to
                // parse the event as `AnySyncTimelineEvent` and
                // match on `MessageLike(RoomMessage(...))` with
                // `MessageType::Text(...)`, which gives us:
                // - automatic skip of non-text messages (`m.image`,
                //   `m.file`, `m.video`, `m.emote`, state events)
                // - a typed `body: String` field (no more
                //   `/content/body` JSON pointer)
                // - the event id and sender typed as
                //   `Option<OwnedEventId>` and `Option<OwnedUserId>`
                //   (we still need strings for `RawPlatformMessage`
                //   so we convert via `to_string()`)
                let raw = event.raw();
                let parsed: Result<matrix_sdk::ruma::events::AnySyncTimelineEvent, _> =
                    raw.deserialize();
                let event_id = event
                    .event_id()
                    .map(|id| id.to_string())
                    .unwrap_or_default();
                let sender = event.sender().map(|s| s.to_string()).unwrap_or_default();
                if let Ok(matrix_sdk::ruma::events::AnySyncTimelineEvent::MessageLike(
                    matrix_sdk::ruma::events::AnySyncMessageLikeEvent::RoomMessage(room_msg),
                )) = parsed
                {
                    // SyncMessageLikeEvent wraps either an
                    // OriginalMessageLikeEvent (with `content`) or
                    // a RedactedMessageLikeEvent (without). The
                    // original is the only one with the message
                    // body we care about.
                    if let Some(original) = room_msg.as_original() {
                        if let matrix_sdk::ruma::events::room::message::MessageType::Text(text) =
                            &original.content.msgtype
                        {
                            if let Ok(payload) = Self::decode_envelope(&text.body) {
                                let mut metadata = std::collections::BTreeMap::new();
                                metadata.insert("sender".to_string(), sender);
                                metadata.insert("event_id".to_string(), event_id.clone());
                                metadata.insert("room_id".to_string(), room_id.to_string());
                                result.push(RawPlatformMessage {
                                    platform_id: event_id,
                                    payload,
                                    metadata,
                                });
                            }
                        }
                    }
                }
            }
        }
        Ok(result)
    }

    fn canonicalize(
        &self,
        raw: &RawPlatformMessage,
    ) -> Result<DeterministicEnvelope, PlatformAdapterError> {
        if raw.payload.is_empty() {
            return Err(transport_err("Empty payload"));
        }
        DeterministicEnvelope::from_wire_bytes(&raw.payload).map_err(|e| {
            PlatformAdapterError::ApiError {
                code: 400,
                message: format!("canonicalize failed: {}", e),
            }
        })
    }

    fn capabilities(&self) -> CapabilityReport {
        CapabilityReport {
            max_payload_bytes: Self::max_payload_bytes(),
            supports_fragmentation: true, // Via media upload
            supports_encryption: false,
            supports_raw_binary: false,
            rate_limit_per_second: Self::rate_limit_per_second(),
            media_capabilities: Some(MediaCapabilities {
                max_upload_bytes: 50 * 1024 * 1024, // 50MB
                supported_mime_types: vec![
                    "image/jpeg".into(),
                    "image/png".into(),
                    "image/gif".into(),
                    "video/mp4".into(),
                    "audio/ogg".into(),
                    "application/pdf".into(),
                    "application/octet-stream".into(),
                ],
            }),
        }
    }

    fn domain_id(&self, platform_id: &str) -> BroadcastDomainId {
        BroadcastDomainId::new(PlatformType::Matrix, platform_id)
    }

    fn platform_type(&self) -> PlatformType {
        PlatformType::Matrix
    }

    fn self_handle(&self) -> Option<String> {
        self.user_id.lock().ok().and_then(|guard| guard.clone())
    }

    async fn shutdown(&self) -> Result<(), PlatformAdapterError> {
        *self.user_id.lock().unwrap() = None;
        *self.next_batch.lock().unwrap() = None;
        Ok(())
    }

    async fn health_check(&self) -> Result<(), PlatformAdapterError> {
        use matrix_sdk::config::SyncSettings;
        use std::time::Duration;

        // Lightweight liveness probe: sync_once with zero timeout
        let sync_settings = SyncSettings::default().timeout(Duration::from_millis(1));

        match tokio::time::timeout(Duration::from_secs(5), self.client.sync_once(sync_settings))
            .await
        {
            Ok(Ok(_)) => {
                // Resolve and cache user_id
                match self.client.whoami().await {
                    Ok(resp) => {
                        let mut guard = self.user_id.lock().unwrap();
                        *guard = Some(resp.user_id.to_string());
                        Ok(())
                    }
                    Err(e) => Err(transport_err(format!("whoami failed: {}", e))),
                }
            }
            Ok(Err(e)) => Err(transport_err(format!("Health check failed: {}", e))),
            Err(_) => Err(transport_err("Health check timed out after 5s")),
        }
    }

    async fn upload_media(
        &self,
        _filename: &str,
        data: &[u8],
        mime_type: &str,
    ) -> Result<String, PlatformAdapterError> {
        let mime: mime::Mime = mime_type
            .parse()
            .map_err(|e| transport_err(format!("Invalid MIME type '{}': {}", mime_type, e)))?;

        let response = self
            .client
            .media()
            .upload(&mime, data.to_vec(), None)
            .await
            .map_err(|e| transport_err(format!("Upload failed: {}", e)))?;

        Ok(response.content_uri.as_str().to_string())
    }

    async fn download_media(&self, media_id: &str) -> Result<Vec<u8>, PlatformAdapterError> {
        use matrix_sdk::ruma::{events::room::MediaSource, OwnedMxcUri};

        let mxc_uri: OwnedMxcUri = media_id.into();

        let request = matrix_sdk::media::MediaRequestParameters {
            source: MediaSource::Plain(mxc_uri),
            format: MediaFormat::File,
        };

        let bytes = self
            .client
            .media()
            .get_media_content(&request, false)
            .await
            .map_err(|e| transport_err(format!("Download failed: {}", e)))?;

        Ok(bytes.to_vec())
    }
}

// --- Plugin ABI exports (for cdylib loading) ---

#[no_mangle]
pub extern "C" fn adapter_version() -> u32 {
    1
}

#[no_mangle]
pub extern "C" fn platform_type() -> u16 {
    0x0003 // Matrix
}

#[no_mangle]
/// # Safety
/// `config` must point to a valid buffer of at least `len` bytes.
pub unsafe extern "C" fn create_adapter(config: *const u8, config_len: usize) -> *mut () {
    if config.is_null() || config_len == 0 {
        set_last_error(MatrixAdapterError::SessionLoad("null config".into()));
        return std::ptr::null_mut();
    }

    let config_bytes = std::slice::from_raw_parts(config, config_len);
    match MatrixAdapter::from_config_bytes(config_bytes) {
        Ok(adapter) => {
            // Clear the last error on a successful construction.
            set_last_error_success();
            Box::into_raw(Box::new(adapter)) as *mut ()
        }
        Err(e) => {
            set_last_error(e);
            std::ptr::null_mut()
        }
    }
}

/// Stash the most recent adapter-construction error so a host that
/// got a null pointer from `create_adapter` can read a stable error
/// string. R1-L14: the previous shape discarded the error entirely.
fn set_last_error(e: MatrixAdapterError) {
    LAST_ERROR.with(|slot| {
        *slot.borrow_mut() = Some(e.to_string());
    });
}

fn set_last_error_success() {
    LAST_ERROR.with(|slot| {
        *slot.borrow_mut() = None;
    });
}

thread_local! {
    static LAST_ERROR: std::cell::RefCell<Option<String>> = const { std::cell::RefCell::new(None) };
}

#[no_mangle]
/// Return the most recent adapter-construction error as a
/// heap-allocated C string. The caller MUST free the returned
/// pointer with `free_last_error`. Returns null on success.
pub extern "C" fn last_error() -> *mut std::os::raw::c_char {
    LAST_ERROR.with(|slot| {
        slot.borrow()
            .as_ref()
            .map(|s| {
                // The pointer is null-terminated; the caller is
                // responsible for freeing it via `free_last_error`.
                std::ffi::CString::new(s.as_str())
                    .map(|c| c.into_raw())
                    .unwrap_or(std::ptr::null_mut())
            })
            .unwrap_or(std::ptr::null_mut())
    })
}

#[no_mangle]
/// # Safety
/// `ptr` must be a pointer previously returned from `last_error`, or
/// null.
pub unsafe extern "C" fn free_last_error(ptr: *mut std::os::raw::c_char) {
    if !ptr.is_null() {
        let _ = std::ffi::CString::from_raw(ptr);
    }
}

#[no_mangle]
/// # Safety
/// `ptr` must be a pointer previously returned by `create_adapter`.
pub unsafe extern "C" fn destroy_adapter(adapter: *mut ()) {
    if !adapter.is_null() {
        let _ = Box::from_raw(adapter as *mut MatrixAdapter);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Each call to `test_config_json` returns a unique `user_id` so the
    /// SDK's SQLite store (path derived from user_id) doesn't collide
    /// across parallel tests. The first run is also serialized on a
    /// per-process unique suffix to avoid collisions across `cargo test`
    /// invocations that re-use the same temp dir.
    ///
    /// `use_session_store: false` forces the adapter to read the
    /// in-process `access_token` field directly (mission 0850h-d's
    /// loader falls back to this when `config_path` is empty and
    /// `use_session_store` is `false`). The adapter's own unit tests
    /// are exercising in-memory crypto, not the stoolap store; the
    /// store's behavior is tested in `octo-matrix-session-store`.
    fn test_config_json() -> serde_json::Value {
        let unique = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0);
        serde_json::json!({
            "homeserver_url": "https://matrix.example.com",
            "user_id": format!("@bot-{}:matrix.example.com", unique),
            "device_id": format!("DEV{}", unique % 1_000_000),
            "access_token": "syt_test",
            "use_session_store": false,
            "rooms": ["!abc:example.com"]
        })
    }

    #[test]
    fn test_encode_decode_envelope() {
        let original = b"test envelope data for matrix";
        let encoded = MatrixAdapter::encode_envelope(original);
        assert!(encoded.starts_with("DOT/1/"));
        let decoded = MatrixAdapter::decode_envelope(&encoded).unwrap();
        assert_eq!(decoded, original);
    }

    #[test]
    fn test_domain_hash_deterministic() {
        let h1 = MatrixAdapter::domain_hash("!abcdef:example.com");
        let h2 = MatrixAdapter::domain_hash("!abcdef:example.com");
        assert_eq!(h1, h2);
    }

    #[test]
    fn test_domain_hash_normalized() {
        let h1 = MatrixAdapter::domain_hash("!abcdef:example.com");
        let h2 = MatrixAdapter::domain_hash("  !abcdef:example.com  ");
        assert_eq!(h1, h2);
    }

    #[test]
    fn test_domain_hash_case_insensitive() {
        let h1 = MatrixAdapter::domain_hash("!ABCDEF:Example.COM");
        let h2 = MatrixAdapter::domain_hash("!abcdef:example.com");
        assert_eq!(h1, h2);
    }

    #[test]
    fn test_platform_type() {
        assert_eq!(MatrixAdapter::PLATFORM_TYPE, 0x0003);
    }

    #[test]
    fn test_abi_exports() {
        assert_eq!(adapter_version(), 1);
        assert_eq!(platform_type(), 0x0003);
    }

    #[test]
    fn test_config_from_json() {
        let config = test_config_json();
        let adapter =
            MatrixAdapter::from_config_bytes(serde_json::to_vec(&config).unwrap().as_slice())
                .unwrap();
        assert_eq!(adapter.config.homeserver_url, "https://matrix.example.com");
        assert_eq!(adapter.config.rooms.len(), 1);
    }

    #[test]
    fn test_capabilities() {
        assert_eq!(MatrixAdapter::max_payload_bytes(), 65536);
        assert_eq!(MatrixAdapter::rate_limit_per_second(), 100);
    }

    #[test]
    fn test_encode_decode_roundtrip() {
        let data = vec![0u8; 1024];
        let encoded = MatrixAdapter::encode_envelope(&data);
        let decoded = MatrixAdapter::decode_envelope(&encoded).unwrap();
        assert_eq!(decoded, data);
    }

    #[test]
    fn test_decode_invalid() {
        assert!(MatrixAdapter::decode_envelope("NOTDOT/1/abc").is_err());
        assert!(MatrixAdapter::decode_envelope("DOT/1/!!!invalid!!!").is_err());
    }

    #[test]
    fn test_largest_payload() {
        let data = vec![0xABu8; 60000];
        let encoded = MatrixAdapter::encode_envelope(&data);
        let decoded = MatrixAdapter::decode_envelope(&encoded).unwrap();
        assert_eq!(decoded, data);
    }

    #[test]
    fn test_adapter_creation() {
        let mut config = test_config_json();
        config["access_token"] = serde_json::json!("syt_test_token_12345");
        let adapter =
            MatrixAdapter::from_config_bytes(serde_json::to_vec(&config).unwrap().as_slice());
        assert!(
            adapter.is_ok(),
            "Adapter creation should succeed: {:?}",
            adapter.err()
        );
    }

    #[test]
    fn test_self_handle_initially_none() {
        let config = test_config_json();
        let adapter =
            MatrixAdapter::from_config_bytes(serde_json::to_vec(&config).unwrap().as_slice())
                .unwrap();
        // After restore_session the bot user_id is cached, so self_handle()
        // returns the bot ID (not None). The user_id is the unique one
        // from test_config_json() (each test gets its own to avoid SQLite
        // store collisions).
        let expected_user = config["user_id"].as_str().unwrap().to_string();
        assert_eq!(adapter.self_handle(), Some(expected_user));
    }

    #[test]
    fn test_config_writeback_fields_default() {
        // Mission 0850h-c: `config_path` and `force_writeback` default
        // to "no writeback" (empty PathBuf, false bool) when absent
        // from the on-disk JSON — old configs that pre-date the
        // mission must continue to deserialize cleanly.
        let mut config = test_config_json();
        config.as_object_mut().unwrap().remove("config_path");
        config.as_object_mut().unwrap().remove("force_writeback");
        let adapter =
            MatrixAdapter::from_config_bytes(serde_json::to_vec(&config).unwrap().as_slice())
                .unwrap();
        assert!(adapter.config.config_path.as_os_str().is_empty());
        assert!(!adapter.config.force_writeback);
    }

    #[test]
    fn test_config_writeback_fields_roundtrip() {
        // Mission 0850h-c: when the host process supplies
        // `force_writeback`, the adapter must capture it for the
        // 401 + refresh path to skip the snapshot check.
        // (`config_path` is tested separately by the
        // session_loader tests; combining them in a single test
        // would require a real on-disk config file.)
        let mut config = test_config_json();
        config["force_writeback"] = serde_json::json!(true);
        let adapter =
            MatrixAdapter::from_config_bytes(serde_json::to_vec(&config).unwrap().as_slice())
                .unwrap();
        assert!(adapter.config.force_writeback);
    }

    #[test]
    fn test_config_path_field_roundtrip() {
        // Mission 0850h-c: `config_path` is a `PathBuf` that survives
        // a JSON roundtrip. We write a real on-disk file at that
        // path (the loader actually reads it) and assert the
        // adapter captured the field.
        let unique = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0);
        let dir = std::env::temp_dir().join(format!("octo-matrix-rc-{unique}"));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("config.json");
        let on_disk = serde_json::json!({
            "homeserver_url": "https://matrix.example.com",
            "user_id": format!("@bot-{}:matrix.example.com", unique),
            "device_id": format!("DEV{}", unique % 1_000_000),
            "access_token": "syt_on_disk",
            "refresh_token": "syr_on_disk",
            "rooms": ["!abc:example.com"]
        });
        std::fs::write(&path, serde_json::to_vec(&on_disk).unwrap()).unwrap();

        let mut config = test_config_json();
        // Override user_id/device_id/access_token so the loader's
        // file read returns the on-disk values (not the
        // `test_config_json` defaults).
        config["user_id"] = on_disk["user_id"].clone();
        config["device_id"] = on_disk["device_id"].clone();
        config["access_token"] = on_disk["access_token"].clone();
        config["config_path"] = serde_json::json!(path.to_string_lossy());
        config["use_session_store"] = serde_json::json!(false);
        let adapter =
            MatrixAdapter::from_config_bytes(serde_json::to_vec(&config).unwrap().as_slice())
                .unwrap();
        assert_eq!(
            adapter.config.config_path.to_str().unwrap(),
            path.to_string_lossy()
        );
    }
}
