//! TV-V1 — byte-exact vault_id derivation vectors.
//!
//! Per review §8.10 + plan §B.3. Each scenario pins (chain_id, owner_did,
//! asset_id) → expected vault_id hex. The fixture loads from
//! `fixtures/tv_v1_vault_id.json` next to this file; vectors are
//! generated by the reference impl (`octo_vault::vault_id_unchecked`)
//! and pinned here for regression detection.
//!
//! Why `vault_id_unchecked` (not `vault_id`): the production `vault_id`
//! `debug_assert!`s reject empty / oversized `owner_did` (Model B §20.3 +
//! substrate-boundary DoS guard). TV-V1-08 + TV-V1-10 intentionally
//! exercise empty inputs to pin the §8.10 wire format at its boundary —
//! `vault_id_unchecked` is the documented escape hatch for fixtures.
//!
//! ## Locked derivation contract (changes here are wire-format breaks)
//!
//! ```text
//! vault_id = BLAKE3("cipherocto/vault/v1/" || chain_id || owner_did || asset_id)
//! ```
//!
//! `chain_id = BLAKE3("cipherocto/chain/v1/" || chain_string)` (§20.3.2)
//! `asset_id  = BLAKE3("cipherocto/asset/v1/" || role_token)`     (§20.3.1)
//!
//! Input ordering is fixed (no length-prefixing); each domain-separator
//! prefix is consumed raw. See `octo_vault::vault_id` for the canonical
//! impl + the in-crate derivation test (`vault_id_is_deterministic` +
//! `vault_id_changes_when_any_input_changes`).
//!
//! ## Test vector set
//!
//! 10 scenarios cover:
//! - TV-V1-01..04: deterministic chain / asset variation
//! - TV-V1-05..07: DID form variation (long, short, with slash)
//! - TV-V1-08..09: cross-chain + cross-asset boundary
//! - TV-V1-10: deterministic edge case (all-empty inputs)
//!
//! ## Sentinel value
//!
//! Per review §20.3 transfer_events: the literal `[0u8; 32]` zero-vault
//! sentinel is reserved for the mint operation (no source vault). It is
//! NOT a derivation output — pinning it here (`VAULT_ZERO_SENTINEL`)
//! alongside TV-V1 prevents downstream consumers from confusing the
//! literal zero with a derived vault_id.

use octo_vault::{vault_id_unchecked, AssetId, ChainId};

/// One TV-V1 scenario: inputs (hex-encoded chain/asset IDs + owner_did) →
/// expected `vault_id` hex. Mirrors the §8.10 central-registry format
/// (per plan §8.10 anchoring table).
#[derive(Debug)]
struct VaultIdVector {
    name: &'static str,
    chain_string: &'static str,
    owner_did: &'static str,
    role_token: &'static str,
    expected_vault_id_hex: &'static str,
}

/// TV-V1 reference vectors. Values generated by the reference impl
/// (`octo_vault::vault_id`) on the same Rust toolchain revision that
/// produced this fixture. Changing the BLAKE3 input layout or the prefix
/// domain tag will break this fixture — that is intentional (the
/// derivation is a wire format; byte-exact lock at the central
/// registry).
const TV_V1_VECTORS: &[VaultIdVector] = &[
    VaultIdVector {
        name: "TV-V1-01_did_octo_test_alice_octo-w_testnet",
        chain_string: "cipherocto/testnet/v1",
        owner_did: "did:octo:test-alice",
        role_token: "OCTO-W",
        expected_vault_id_hex: TV_V1_01,
    },
    VaultIdVector {
        name: "TV-V1-02_did_octo_test_bob_octo-w_testnet",
        chain_string: "cipherocto/testnet/v1",
        owner_did: "did:octo:test-bob",
        role_token: "OCTO-W",
        expected_vault_id_hex: TV_V1_02,
    },
    VaultIdVector {
        name: "TV-V1-03_did_octo_test_alice_octo-a_testnet",
        chain_string: "cipherocto/testnet/v1",
        owner_did: "did:octo:test-alice",
        role_token: "OCTO-A",
        expected_vault_id_hex: TV_V1_03,
    },
    VaultIdVector {
        name: "TV-V1-04_did_octo_test_alice_octo-w_mainnet",
        chain_string: "cipherocto/mainnet/v1",
        owner_did: "did:octo:test-alice",
        role_token: "OCTO-W",
        expected_vault_id_hex: TV_V1_04,
    },
    VaultIdVector {
        name: "TV-V1-05_long_did_with_slash_octo-w_testnet",
        chain_string: "cipherocto/testnet/v1",
        owner_did: "did:octo:long-form-identifier-with-many-segments/and/nested/path",
        role_token: "OCTO-W",
        expected_vault_id_hex: TV_V1_05,
    },
    VaultIdVector {
        name: "TV-V1-06_short_did_min_form_octo-w_testnet",
        chain_string: "cipherocto/testnet/v1",
        owner_did: "did:octo:x",
        role_token: "OCTO-W",
        expected_vault_id_hex: TV_V1_06,
    },
    VaultIdVector {
        name: "TV-V1-07_unicode_did_octo-w_testnet",
        chain_string: "cipherocto/testnet/v1",
        owner_did: "did:octo:ß",
        role_token: "OCTO-W",
        expected_vault_id_hex: TV_V1_07,
    },
    VaultIdVector {
        name: "TV-V1-08_empty_owner_did_derivation_deterministic",
        chain_string: "cipherocto/testnet/v1",
        owner_did: "",
        role_token: "OCTO-W",
        expected_vault_id_hex: TV_V1_08,
    },
    VaultIdVector {
        name: "TV-V1-09_cross_chain_cross_asset_boundary",
        chain_string: "cipherocto/mainnet/v1",
        owner_did: "did:octo:test-bob",
        role_token: "OCTO-A",
        expected_vault_id_hex: TV_V1_09,
    },
    VaultIdVector {
        name: "TV-V1-10_all_empty_inputs_edge_case",
        chain_string: "",
        owner_did: "",
        role_token: "",
        expected_vault_id_hex: TV_V1_10,
    },
];

/// Hash every known TV-V1 vector and assert it matches the pinned hex.
#[test]
fn tv_v1_vault_id_vectors_match_pinned_hex() {
    for v in TV_V1_VECTORS {
        let chain_id = ChainId::derive(v.chain_string);
        let asset_id = AssetId::derive(v.role_token);
        let id = vault_id_unchecked(chain_id, v.owner_did, asset_id);
        let actual_hex = hex::encode(id.as_bytes());
        assert_eq!(
            actual_hex, v.expected_vault_id_hex,
            "TV-V1 vector drift: {} (chain='{}', owner='{}', asset='{}')\n  actual:   {}\n  expected: {}",
            v.name, v.chain_string, v.owner_did, v.role_token,
            actual_hex, v.expected_vault_id_hex
        );
    }
}

// ----- Byte-locked expected hex values (generated by reference impl) -----
//
// 32-byte BLAKE3 outputs in lowercase hex, 64 chars per vector. Generated
// 2026-08-16 by `octo_vault::vault_id` over the inputs above. Regenerate
// via `cargo run -p octo-vault --example capture_tv_v1` (see the `examples/`
// dir) — copy from stdout back into the constants below.
//
// These constants ARE the lock. A mismatch between the reference impl and
// the constants here breaks the test — go fix the impl OR fix the inputs,
// never both.

const TV_V1_01: &str = "2d5b470ba690b80ea35d5a60c864014304fd72a52093c0ad66ba9290d153691c";
const TV_V1_02: &str = "15e6dc8e1a8ad6ac0154ff6e37542c45240c5e60afea090c254fffebea1ab005";
const TV_V1_03: &str = "933cf5e9faad773123e152adc9086ee3c553d4250e51c2d649dcf44a8a521507";
const TV_V1_04: &str = "c9865eb6a7bd0f4bb3421f90d1a8531558d3e1cd6ba1696bce0ffea4ee9f264c";
const TV_V1_05: &str = "0802967ed296b4952627db7c6efd109ec062476623c21c6431731b6d08dd455c";
const TV_V1_06: &str = "0daf5a1015f93e65479e17f7e02bc8961919c281c57d18782a5ffa7f3540576b";
const TV_V1_07: &str = "118c29c7b438a3aab3ce76de3c78d233d97987c84be837685334529633abc401";
const TV_V1_08: &str = "7c3ce4092304130eb7bb7151fbd9484d43f154f560430acb2d2a45c481383476";
const TV_V1_09: &str = "7b925bbabda7c5db5f8973605ee3f05c96e5a9e7bac5e0c9c5a40c64c537f239";
const TV_V1_10: &str = "de71a9d8e25af74c288e890b029283451634e048b1c7a2f4205075227415f161";

/// Reserved mint sentinel per review §20.3: a literal `[0u8; 32]` used as
/// `from_vault_id` in the `transfer_events` table when minting new supply
/// (no source vault exists). NOT a derivation output — pinning it here
/// keeps downstream consumers from confusing it with a BLAKE3-derived
/// vault_id (which can never be all-zero by cryptographic design).
pub const VAULT_ZERO_SENTINEL: [u8; 32] = [0u8; 32];

#[test]
fn zero_vault_sentinel_is_literal_all_zeros() {
    // Sanity-check the pin: every byte must be zero, the value must NOT
    // match any TV-V1 hex (which are BLAKE3 outputs and therefore cannot
    // be all-zero by hash properties).
    assert!(VAULT_ZERO_SENTINEL.iter().all(|&b| b == 0));
    for v in TV_V1_VECTORS {
        let zero_hex = hex::encode(VAULT_ZERO_SENTINEL);
        assert_ne!(
            zero_hex, v.expected_vault_id_hex,
            "VAULT_ZERO_SENTINEL collides with {} (impossible if both pins correct)",
            v.name
        );
    }
}

// ===========================================================================
// TV-D9 — byte-exact asset_id derivation vectors (RFC-0105 v2.0, mission 0105-v)
// ===========================================================================
//
// 9 canonical role-token × asset_id mappings per review §20.3.1 +
// review §1336 cross-section reconciliation. Each `(role_token,
// asset_id_hex)` is the §8.10 canonical anchor — byte-exact
// identical across all implementations (BLAKE3-256 of
// "cipherocto/asset/v1/" || role_token).
//
// Domain-separation: namespace `"cipherocto/asset/v1/"` (constant in
// `octo_determin::ASSET_ID_DOMAIN_V1`) — future version bumps
// (`v2`, ...) guarantee collision-free asset IDs across ecosystem
// forks.
//
// Sovereign OCTO is EXCLUDED from this TV set (cross-layer
// capability-attestation path; see review §1336 + §1362).

use octo_determin::{asset_id_for, ROLE_TOKENS};

/// One TV-D9 scenario: `role_token` → expected `asset_id` hex. Pinned
/// here for §8.10 central-registry anchoring.
#[derive(Debug)]
struct AssetIdVector {
    /// Human-readable role-token discriminator (e.g., `"OCTO-A"`).
    role_token: &'static str,
    /// Short label for diagnostics (e.g., `"TV-D9-01"`).
    name: &'static str,
    /// Hex-encoded expected `asset_id` ([u8; 32] → 64 hex chars).
    asset_id_hex: &'static str,
}

/// 9 canonical vectors per review §1336. Sovereign OCTO excluded.
const TV_D9_VECTORS: &[AssetIdVector] = &[
    AssetIdVector {
        role_token: "OCTO-A",
        name: "TV-D9-01: AI Compute",
        asset_id_hex: "161e52f483cf25de1163a0d6dccce98c50404971065de3b1013aaeaa64e1a01b",
    },
    AssetIdVector {
        role_token: "OCTO-B",
        name: "TV-D9-02: Bandwidth",
        asset_id_hex: "5ca7f59fe932648a0327c29060326a2fe6ad60131d5b38639f15c720d9ce3c0a",
    },
    AssetIdVector {
        role_token: "OCTO-D",
        name: "TV-D9-03: Developers",
        asset_id_hex: "c5180b712f27cc8e0d72dc7d91217e6526fd8eaaa526ac5d83b62c29ffe7a581",
    },
    AssetIdVector {
        role_token: "OCTO-M",
        name: "TV-D9-04: Marketing",
        asset_id_hex: "8aa463d5d06c35ea75abca875ef7787945db0c321d609e6e6e1a8fec21caf64a",
    },
    AssetIdVector {
        role_token: "OCTO-N",
        name: "TV-D9-05: Node Operators",
        asset_id_hex: "b940c7dc0087fd559a626d8047881ac4e620282e112bdcf6fb437a374cf64091",
    },
    AssetIdVector {
        role_token: "OCTO-O",
        name: "TV-D9-06: Orchestrator",
        asset_id_hex: "d2cf354857f5612e78a35c9d307885a1e3428804c5bda2c4b3cb4ae2e1e2ca4a",
    },
    AssetIdVector {
        role_token: "OCTO-S",
        name: "TV-D9-07: Storage",
        asset_id_hex: "fc97983dcb4b30e8cd9d893f4784ffcaaa6d3fc585129b6554a658dac40f5f36",
    },
    AssetIdVector {
        role_token: "OCTO-H",
        name: "TV-D9-08: Historical",
        asset_id_hex: "72a20d851da06aaeaa34451a79bf70633d8e3b2553e4c86606864d98ef4a2483",
    },
    AssetIdVector {
        role_token: "OCTO-W",
        name: "TV-D9-09: AI Wholesale",
        asset_id_hex: "24fadb2b4f5eebc5f6199f3ee4625f64d8d7c822413c700309f09b0ad1b281b0",
    },
];

/// Decode a 64-char hex string to a `[u8; 32]`.
fn decode_asset_id_hex(hex: &str) -> [u8; 32] {
    let bytes = hex::decode(hex).expect("TV-D9 hex is well-formed");
    assert_eq!(bytes.len(), 32, "TV-D9 hex MUST decode to 32 bytes");
    let mut out = [0u8; 32];
    out.copy_from_slice(&bytes);
    out
}

/// TV-D9 byte-exact anchor: every canonical role-token MUST produce
/// the pinned `asset_id` (per §8.10 + §20.3.1). Cross-implementation
/// regression detector — if any vector drifts, the BLAKE3 chain or
/// domain separator changed.
#[test]
fn tv_d9_asset_id_vectors_match_pinned_hex() {
    for v in TV_D9_VECTORS {
        let computed = asset_id_for(v.role_token);
        let expected = decode_asset_id_hex(v.asset_id_hex);
        assert_eq!(
            computed,
            expected,
            "TV-D9 asset_id drift on {} (role_token={:?}): expected {}, got {}",
            v.name,
            v.role_token,
            v.asset_id_hex,
            hex::encode(computed),
        );
    }
}

/// TV-D9 enumeration exhaustiveness: every entry in
/// `ROLE_TOKENS` MUST appear in `TV_D9_VECTORS` (and vice versa).
/// Catches a future RFC change that adds/removes a role-token
/// without updating the TV central registry.
#[test]
fn tv_d9_vectors_cover_role_tokens_exactly_once() {
    use std::collections::HashSet;
    let tv_tokens: HashSet<&str> = TV_D9_VECTORS.iter().map(|v| v.role_token).collect();
    let role_tokens: HashSet<&str> = ROLE_TOKENS.iter().copied().collect();
    assert_eq!(
        tv_tokens, role_tokens,
        "TV-D9 vector set MUST equal ROLE_TOKENS (cross-section drift)"
    );
}

/// Cross-check: `octo_determin::asset_id_for` MUST match
/// `octo_vault::AssetId::derive` byte-by-byte (the Layer B
/// substrate's local derivation must agree with the Layer A
/// canonical derivation). Catches a future drift where the
/// substrate's derivation gets out of sync with the canonical
/// rule (regression: silent identity-key drift).
#[test]
fn asset_id_for_matches_octo_vault_asset_id_derive() {
    for rt in ROLE_TOKENS {
        let canonical = asset_id_for(rt);
        let substrate = octo_vault::AssetId::derive(rt);
        assert_eq!(
            canonical,
            *substrate.as_bytes(),
            "asset_id_for({rt:?}) MUST match AssetId::derive byte-by-byte"
        );
    }
}

// ===========================================================================
// TV-D10 — 100 DQA arithmetic determinism fixtures (RFC-0105, mission 0105-v)
// ===========================================================================
//
// 100 distinct arithmetic combinations grouped into 10 categories of
// 10 fixtures each, per review §24 per-RFC TV allocation. Categories
// cover: add, sub, mul, div, overflow-saturation, negative-result,
// zero-operand, scale-alignment, rounding-boundary, cross-scale-mix.
//
// ## Fixture shape
//
// Each fixture pins `(scale_a, value_a) × op × (scale_b, value_b)` —
// the canonical Layer A DQA substrate is responsible for the actual
// result (scale-promote + canonicalize + RNE rounding per
// RFC-0105 §Arithmetic Algorithms). The test asserts:
//
// 1. **Determinism**: the same input pair MUST produce the same
//    `(value, scale)` on every run, on every platform (Layer A
//    cross-implementation byte-stability).
//
// 2. **Scale invariants**: result.scale ≤ 18, result.value fits in
//    i64, result.value is canonical (no redundant trailing-zero
//    scale shifts).
//
// 3. **Reproducibility**: each fixture's result is captured into a
//    JSON snapshot at `tv_d10_snapshot.json` (test-only artifact) on
//    first run; subsequent runs MUST match. This is the
//    cross-implementation byte anchor — a future change to
//    `canonicalize` / `round_half_even` / `align_scales` will flip
//    the captured result and fail the test.
//
// `octo_determin::Dqa` is the canonical Layer A substrate type
// (RFC-0105 §Data Structures); the byte anchor is the 16-byte BE
// `DqaEncoding` wire form (RFC-0862 v1.x AC #4 cross-ref).

use octo_determin::dqa::Dqa;
use std::sync::OnceLock;

/// Arithmetic op tag for TV-D10 fixtures.
#[derive(Debug, Clone, Copy)]
#[allow(non_camel_case_types)]
enum Op {
    Add,
    Sub,
    Mul,
    Div,
}

/// One TV-D10 scenario: `(scale_a, value_a) × op × (scale_b, value_b)`.
/// The expected (value, scale) is captured at first run from the
/// canonical `Dqa` impl (deterministic across platforms).
struct DqaRoundTripVector {
    label: &'static str,
    op: Op,
    scale_a: u8,
    value_a: i64,
    scale_b: u8,
    value_b: i64,
}

impl std::fmt::Display for DqaRoundTripVector {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.label)
    }
}

/// 100 fixtures = 10 categories × 10 each.
const TV_D10_VECTORS: &[DqaRoundTripVector] = &[
    // ----- Category 1: addition (10 fixtures) -----
    DqaRoundTripVector {
        label: "TV-D10-add-01: 0-scale positive + 0-scale positive",
        op: Op::Add,
        scale_a: 0,
        value_a: 100,
        scale_b: 0,
        value_b: 200,
    },
    DqaRoundTripVector {
        label: "TV-D10-add-02: 0-scale positive + 0-scale negative",
        op: Op::Add,
        scale_a: 0,
        value_a: 100,
        scale_b: 0,
        value_b: -50,
    },
    DqaRoundTripVector {
        label: "TV-D10-add-03: 0-scale zero + 0-scale positive",
        op: Op::Add,
        scale_a: 0,
        value_a: 0,
        scale_b: 0,
        value_b: 999,
    },
    DqaRoundTripVector {
        label: "TV-D10-add-04: 3-scale + 3-scale (same scale align)",
        op: Op::Add,
        scale_a: 3,
        value_a: 1_000,
        scale_b: 3,
        value_b: 2_500,
    },
    DqaRoundTripVector {
        label: "TV-D10-add-05: 3-scale + 5-scale (scale promote)",
        op: Op::Add,
        scale_a: 3,
        value_a: 1_000,
        scale_b: 5,
        value_b: 250_000,
    },
    DqaRoundTripVector {
        label: "TV-D10-add-06: 12-scale (DQA(12) compatible)",
        op: Op::Add,
        scale_a: 12,
        value_a: 1_500_000_000,
        scale_b: 12,
        value_b: 2_500_000_000,
    },
    DqaRoundTripVector {
        label: "TV-D10-add-07: 0-scale + 12-scale (promote)",
        op: Op::Add,
        scale_a: 0,
        value_a: 4,
        scale_b: 12,
        value_b: 4_000_000_000_000,
    },
    DqaRoundTripVector {
        label: "TV-D10-add-08: 18-scale (max) + 0-scale (promote)",
        op: Op::Add,
        scale_a: 18,
        value_a: 1_000_000_000_000_000_000,
        scale_b: 0,
        value_b: 5,
    },
    DqaRoundTripVector {
        label: "TV-D10-add-09: overflow (i64::MAX + 1 → overflow)",
        op: Op::Add,
        scale_a: 0,
        value_a: i64::MAX,
        scale_b: 0,
        value_b: 1,
    },
    DqaRoundTripVector {
        label: "TV-D10-add-10: underflow (i64::MIN + -1 → overflow)",
        op: Op::Add,
        scale_a: 0,
        value_a: i64::MIN,
        scale_b: 0,
        value_b: -1,
    },
    // ----- Category 2: subtraction (10 fixtures) -----
    DqaRoundTripVector {
        label: "TV-D10-sub-01: 0-scale positive - 0-scale positive",
        op: Op::Sub,
        scale_a: 0,
        value_a: 200,
        scale_b: 0,
        value_b: 100,
    },
    DqaRoundTripVector {
        label: "TV-D10-sub-02: 0-scale positive - 0-scale negative",
        op: Op::Sub,
        scale_a: 0,
        value_a: 100,
        scale_b: 0,
        value_b: -50,
    },
    DqaRoundTripVector {
        label: "TV-D10-sub-03: 0-scale zero - 0-scale positive",
        op: Op::Sub,
        scale_a: 0,
        value_a: 0,
        scale_b: 0,
        value_b: 500,
    },
    DqaRoundTripVector {
        label: "TV-D10-sub-04: 3-scale - 3-scale",
        op: Op::Sub,
        scale_a: 3,
        value_a: 5_000,
        scale_b: 3,
        value_b: 2_000,
    },
    DqaRoundTripVector {
        label: "TV-D10-sub-05: 3-scale - 5-scale (promote)",
        op: Op::Sub,
        scale_a: 3,
        value_a: 1_000,
        scale_b: 5,
        value_b: 250_000,
    },
    DqaRoundTripVector {
        label: "TV-D10-sub-06: 12-scale subtraction",
        op: Op::Sub,
        scale_a: 12,
        value_a: 5_000_000_000,
        scale_b: 12,
        value_b: 2_000_000_000,
    },
    DqaRoundTripVector {
        label: "TV-D10-sub-07: 0-scale - 12-scale (promote)",
        op: Op::Sub,
        scale_a: 0,
        value_a: 4,
        scale_b: 12,
        value_b: 8_000_000_000_000,
    },
    DqaRoundTripVector {
        label: "TV-D10-sub-08: overflow (i64::MIN - 1)",
        op: Op::Sub,
        scale_a: 0,
        value_a: i64::MIN,
        scale_b: 0,
        value_b: 1,
    },
    DqaRoundTripVector {
        label: "TV-D10-sub-09: underflow (i64::MAX - -1)",
        op: Op::Sub,
        scale_a: 0,
        value_a: i64::MAX,
        scale_b: 0,
        value_b: -1,
    },
    DqaRoundTripVector {
        label: "TV-D10-sub-10: zero result (x - x)",
        op: Op::Sub,
        scale_a: 7,
        value_a: 123_456_789,
        scale_b: 7,
        value_b: 123_456_789,
    },
    // ----- Category 3: multiplication (10 fixtures) -----
    DqaRoundTripVector {
        label: "TV-D10-mul-01: 0-scale * 0-scale",
        op: Op::Mul,
        scale_a: 0,
        value_a: 7,
        scale_b: 0,
        value_b: 11,
    },
    DqaRoundTripVector {
        label: "TV-D10-mul-02: zero * positive",
        op: Op::Mul,
        scale_a: 0,
        value_a: 0,
        scale_b: 0,
        value_b: 1_000,
    },
    DqaRoundTripVector {
        label: "TV-D10-mul-03: negative * negative = positive",
        op: Op::Mul,
        scale_a: 0,
        value_a: -100,
        scale_b: 0,
        value_b: -200,
    },
    DqaRoundTripVector {
        label: "TV-D10-mul-04: negative * positive = negative",
        op: Op::Mul,
        scale_a: 0,
        value_a: -50,
        scale_b: 0,
        value_b: 300,
    },
    DqaRoundTripVector {
        label: "TV-D10-mul-05: 3-scale * 3-scale (scale promote)",
        op: Op::Mul,
        scale_a: 3,
        value_a: 1_500,
        scale_b: 3,
        value_b: 2_000,
    },
    DqaRoundTripVector {
        label: "TV-D10-mul-06: 12-scale * 12-scale (overflow)",
        op: Op::Mul,
        scale_a: 12,
        value_a: 1_500_000_000_000,
        scale_b: 12,
        value_b: 2_000_000_000_000,
    },
    DqaRoundTripVector {
        label: "TV-D10-mul-07: 0-scale * 18-scale (promote)",
        op: Op::Mul,
        scale_a: 0,
        value_a: 6,
        scale_b: 18,
        value_b: 1_000_000_000_000_000_000,
    },
    DqaRoundTripVector {
        label: "TV-D10-mul-08: 7-scale * 5-scale (promote)",
        op: Op::Mul,
        scale_a: 7,
        value_a: 123_456,
        scale_b: 5,
        value_b: 654_321,
    },
    DqaRoundTripVector {
        label: "TV-D10-mul-09: overflow (i64::MAX * 2)",
        op: Op::Mul,
        scale_a: 0,
        value_a: i64::MAX,
        scale_b: 0,
        value_b: 2,
    },
    DqaRoundTripVector {
        label: "TV-D10-mul-10: scale-promote beyond 18",
        op: Op::Mul,
        scale_a: 18,
        value_a: 1_000_000_000_000_000_000,
        scale_b: 18,
        value_b: 1_000_000_000_000_000_000,
    },
    // ----- Category 4: division (10 fixtures) -----
    DqaRoundTripVector {
        label: "TV-D10-div-01: 0-scale / 0-scale exact",
        op: Op::Div,
        scale_a: 0,
        value_a: 100,
        scale_b: 0,
        value_b: 4,
    },
    DqaRoundTripVector {
        label: "TV-D10-div-02: 0-scale / 0-scale with remainder (RNE)",
        op: Op::Div,
        scale_a: 0,
        value_a: 100,
        scale_b: 0,
        value_b: 3,
    },
    DqaRoundTripVector {
        label: "TV-D10-div-03: 0-scale negative / 0-scale positive",
        op: Op::Div,
        scale_a: 0,
        value_a: -100,
        scale_b: 0,
        value_b: 5,
    },
    DqaRoundTripVector {
        label: "TV-D10-div-04: 0-scale 0 / 0-scale positive = 0",
        op: Op::Div,
        scale_a: 0,
        value_a: 0,
        scale_b: 0,
        value_b: 1_000,
    },
    DqaRoundTripVector {
        label: "TV-D10-div-05: 12-scale / 12-scale exact",
        op: Op::Div,
        scale_a: 12,
        value_a: 4_000_000_000_000,
        scale_b: 12,
        value_b: 2_000_000_000_000,
    },
    DqaRoundTripVector {
        label: "TV-D10-div-06: 12-scale / 0-scale",
        op: Op::Div,
        scale_a: 12,
        value_a: 4_000_000_000_000,
        scale_b: 0,
        value_b: 2,
    },
    DqaRoundTripVector {
        label: "TV-D10-div-07: 0-scale / 12-scale (truncate)",
        op: Op::Div,
        scale_a: 0,
        value_a: 1,
        scale_b: 12,
        value_b: 3_000_000_000_000,
    },
    DqaRoundTripVector {
        label: "TV-D10-div-08: 18-scale / 18-scale exact",
        op: Op::Div,
        scale_a: 18,
        value_a: 1_000_000_000_000_000_000,
        scale_b: 18,
        value_b: 1_000_000_000_000_000_000,
    },
    DqaRoundTripVector {
        label: "TV-D10-div-09: RNE half-even boundary",
        op: Op::Div,
        scale_a: 0,
        value_a: 10,
        scale_b: 0,
        value_b: 4,
    },
    DqaRoundTripVector {
        label: "TV-D10-div-10: 12-scale large / 12-scale 1",
        op: Op::Div,
        scale_a: 12,
        value_a: 9_999_999_999_999,
        scale_b: 12,
        value_b: 1_000_000_000_000,
    },
    // ----- Category 5: overflow-saturation edges (10 fixtures) -----
    DqaRoundTripVector {
        label: "TV-D10-ovf-01: add overflow",
        op: Op::Add,
        scale_a: 0,
        value_a: i64::MAX - 100,
        scale_b: 0,
        value_b: 200,
    },
    DqaRoundTripVector {
        label: "TV-D10-ovf-02: sub underflow",
        op: Op::Sub,
        scale_a: 0,
        value_a: i64::MIN + 100,
        scale_b: 0,
        value_b: 200,
    },
    DqaRoundTripVector {
        label: "TV-D10-ovf-03: mul overflow",
        op: Op::Mul,
        scale_a: 0,
        value_a: i64::MAX,
        scale_b: 0,
        value_b: 10,
    },
    DqaRoundTripVector {
        label: "TV-D10-ovf-04: mul 12-scale overflow",
        op: Op::Mul,
        scale_a: 12,
        value_a: 999_999_999_999,
        scale_b: 12,
        value_b: 999_999_999_999,
    },
    DqaRoundTripVector {
        label: "TV-D10-ovf-05: scale-promotion across 18 → sat",
        op: Op::Mul,
        scale_a: 12,
        value_a: 1_000_000_000_000,
        scale_b: 12,
        value_b: 1_000_000_000_000,
    },
    DqaRoundTripVector {
        label: "TV-D10-ovf-06: add just below overflow (no sat)",
        op: Op::Add,
        scale_a: 0,
        value_a: i64::MAX - 1,
        scale_b: 0,
        value_b: 1,
    },
    DqaRoundTripVector {
        label: "TV-D10-ovf-07: sub just above underflow (no sat)",
        op: Op::Sub,
        scale_a: 0,
        value_a: i64::MIN + 1,
        scale_b: 0,
        value_b: 1,
    },
    DqaRoundTripVector {
        label: "TV-D10-ovf-08: mul neg * neg fits",
        op: Op::Mul,
        scale_a: 0,
        value_a: -1_000_000_000,
        scale_b: 0,
        value_b: -2_000_000_000,
    },
    DqaRoundTripVector {
        label: "TV-D10-ovf-09: mul near-bound (i64::MAX/2 * 3)",
        op: Op::Mul,
        scale_a: 0,
        value_a: i64::MAX / 2,
        scale_b: 0,
        value_b: 3,
    },
    DqaRoundTripVector {
        label: "TV-D10-ovf-10: scale-promote beyond 18",
        op: Op::Mul,
        scale_a: 12,
        value_a: 1_500_000_000_000,
        scale_b: 12,
        value_b: 2_000_000_000_000,
    },
    // ----- Category 6: negative-result accounting (10 fixtures) -----
    DqaRoundTripVector {
        label: "TV-D10-neg-01: add 0-scale neg + 0-scale neg",
        op: Op::Add,
        scale_a: 0,
        value_a: -100,
        scale_b: 0,
        value_b: -200,
    },
    DqaRoundTripVector {
        label: "TV-D10-neg-02: add neg + pos",
        op: Op::Add,
        scale_a: 0,
        value_a: -100,
        scale_b: 0,
        value_b: 50,
    },
    DqaRoundTripVector {
        label: "TV-D10-neg-03: sub neg - pos = more negative",
        op: Op::Sub,
        scale_a: 0,
        value_a: -100,
        scale_b: 0,
        value_b: 50,
    },
    DqaRoundTripVector {
        label: "TV-D10-neg-04: sub pos - neg",
        op: Op::Sub,
        scale_a: 0,
        value_a: 100,
        scale_b: 0,
        value_b: -50,
    },
    DqaRoundTripVector {
        label: "TV-D10-neg-05: mul pos * neg",
        op: Op::Mul,
        scale_a: 0,
        value_a: 100,
        scale_b: 0,
        value_b: -3,
    },
    DqaRoundTripVector {
        label: "TV-D10-neg-06: mul neg * pos",
        op: Op::Mul,
        scale_a: 0,
        value_a: -100,
        scale_b: 0,
        value_b: 3,
    },
    DqaRoundTripVector {
        label: "TV-D10-neg-07: 12-scale negative round-trip",
        op: Op::Add,
        scale_a: 12,
        value_a: -1_500_000_000_000,
        scale_b: 12,
        value_b: 500_000_000_000,
    },
    DqaRoundTripVector {
        label: "TV-D10-neg-08: zero - neg = pos",
        op: Op::Sub,
        scale_a: 0,
        value_a: 0,
        scale_b: 0,
        value_b: -42,
    },
    DqaRoundTripVector {
        label: "TV-D10-neg-09: neg - zero = neg",
        op: Op::Sub,
        scale_a: 0,
        value_a: -42,
        scale_b: 0,
        value_b: 0,
    },
    DqaRoundTripVector {
        label: "TV-D10-neg-10: 0 - 0",
        op: Op::Sub,
        scale_a: 0,
        value_a: 0,
        scale_b: 0,
        value_b: 0,
    },
    // ----- Category 7: zero-operand algebra (10 fixtures) -----
    DqaRoundTripVector {
        label: "TV-D10-zero-01: 0 + 0",
        op: Op::Add,
        scale_a: 0,
        value_a: 0,
        scale_b: 0,
        value_b: 0,
    },
    DqaRoundTripVector {
        label: "TV-D10-zero-02: 0 + pos",
        op: Op::Add,
        scale_a: 0,
        value_a: 0,
        scale_b: 0,
        value_b: 42,
    },
    DqaRoundTripVector {
        label: "TV-D10-zero-03: pos + 0 (commutative)",
        op: Op::Add,
        scale_a: 0,
        value_a: 42,
        scale_b: 0,
        value_b: 0,
    },
    DqaRoundTripVector {
        label: "TV-D10-zero-04: 0 * pos",
        op: Op::Mul,
        scale_a: 5,
        value_a: 0,
        scale_b: 5,
        value_b: 99_999,
    },
    DqaRoundTripVector {
        label: "TV-D10-zero-05: 0 / pos = 0",
        op: Op::Div,
        scale_a: 0,
        value_a: 0,
        scale_b: 0,
        value_b: 100,
    },
    DqaRoundTripVector {
        label: "TV-D10-zero-06: 0 * 12-scale",
        op: Op::Mul,
        scale_a: 0,
        value_a: 0,
        scale_b: 12,
        value_b: 999_999_999_999,
    },
    DqaRoundTripVector {
        label: "TV-D10-zero-07: 12-scale 0 + 0",
        op: Op::Add,
        scale_a: 12,
        value_a: 0,
        scale_b: 12,
        value_b: 0,
    },
    DqaRoundTripVector {
        label: "TV-D10-zero-08: sub 0 - 0",
        op: Op::Sub,
        scale_a: 3,
        value_a: 0,
        scale_b: 3,
        value_b: 0,
    },
    DqaRoundTripVector {
        label: "TV-D10-zero-09: mul at 0-scale 0",
        op: Op::Mul,
        scale_a: 0,
        value_a: 0,
        scale_b: 0,
        value_b: 0,
    },
    DqaRoundTripVector {
        label: "TV-D10-zero-10: 18-scale 0 + 18-scale 1",
        op: Op::Add,
        scale_a: 18,
        value_a: 0,
        scale_b: 18,
        value_b: 1,
    },
    // ----- Category 8: scale-alignment promotion (10 fixtures) -----
    DqaRoundTripVector {
        label: "TV-D10-scale-01: 0 + 1 (promote to 1)",
        op: Op::Add,
        scale_a: 0,
        value_a: 5,
        scale_b: 1,
        value_b: 30,
    },
    DqaRoundTripVector {
        label: "TV-D10-scale-02: 1 + 0 (promote to 1)",
        op: Op::Add,
        scale_a: 1,
        value_a: 30,
        scale_b: 0,
        value_b: 5,
    },
    DqaRoundTripVector {
        label: "TV-D10-scale-03: 6 + 12 (promote)",
        op: Op::Add,
        scale_a: 6,
        value_a: 1_234_567,
        scale_b: 12,
        value_b: 1_234_567_891_012,
    },
    DqaRoundTripVector {
        label: "TV-D10-scale-04: 12 + 6 (symmetric)",
        op: Op::Add,
        scale_a: 12,
        value_a: 1_234_567_891_012,
        scale_b: 6,
        value_b: 1_234_567,
    },
    DqaRoundTripVector {
        label: "TV-D10-scale-05: 12 sub 0 (no promote)",
        op: Op::Sub,
        scale_a: 12,
        value_a: 5_000_000_000_000,
        scale_b: 0,
        value_b: 3,
    },
    DqaRoundTripVector {
        label: "TV-D10-scale-06: 0 mul 18 (promote)",
        op: Op::Mul,
        scale_a: 0,
        value_a: 7,
        scale_b: 18,
        value_b: 1_000_000_000_000_000_000,
    },
    DqaRoundTripVector {
        label: "TV-D10-scale-07: 18 mul 0 (symmetric)",
        op: Op::Mul,
        scale_a: 18,
        value_a: 1_000_000_000_000_000_000,
        scale_b: 0,
        value_b: 7,
    },
    DqaRoundTripVector {
        label: "TV-D10-scale-08: 3 div 0 (truncate)",
        op: Op::Div,
        scale_a: 3,
        value_a: 1_000,
        scale_b: 0,
        value_b: 3,
    },
    DqaRoundTripVector {
        label: "TV-D10-scale-09: 0 div 12 (truncate)",
        op: Op::Div,
        scale_a: 0,
        value_a: 5,
        scale_b: 12,
        value_b: 1_000_000_000_000,
    },
    DqaRoundTripVector {
        label: "TV-D10-scale-10: full 18-scale add (max boundary)",
        op: Op::Add,
        scale_a: 18,
        value_a: 999_999_999_999_999_999,
        scale_b: 18,
        value_b: 1,
    },
    // ----- Category 9: rounding-boundary edges (10 fixtures) -----
    DqaRoundTripVector {
        label: "TV-D10-round-01: div 1/2 → 0 (RNE truncate)",
        op: Op::Div,
        scale_a: 0,
        value_a: 1,
        scale_b: 0,
        value_b: 2,
    },
    DqaRoundTripVector {
        label: "TV-D10-round-02: div 5/2 → 2 (RNE truncate)",
        op: Op::Div,
        scale_a: 0,
        value_a: 5,
        scale_b: 0,
        value_b: 2,
    },
    DqaRoundTripVector {
        label: "TV-D10-round-03: div -5/2 → -2 (RNE)",
        op: Op::Div,
        scale_a: 0,
        value_a: -5,
        scale_b: 0,
        value_b: 2,
    },
    DqaRoundTripVector {
        label: "TV-D10-round-04: div 7/2 → 3",
        op: Op::Div,
        scale_a: 0,
        value_a: 7,
        scale_b: 0,
        value_b: 2,
    },
    DqaRoundTripVector {
        label: "TV-D10-round-05: div -7/2 → -3",
        op: Op::Div,
        scale_a: 0,
        value_a: -7,
        scale_b: 0,
        value_b: 2,
    },
    DqaRoundTripVector {
        label: "TV-D10-round-06: div 100/3 → 33",
        op: Op::Div,
        scale_a: 0,
        value_a: 100,
        scale_b: 0,
        value_b: 3,
    },
    DqaRoundTripVector {
        label: "TV-D10-round-07: div 12-scale 1 / 12-scale 3 = 0",
        op: Op::Div,
        scale_a: 12,
        value_a: 1_000_000_000_000,
        scale_b: 12,
        value_b: 3_000_000_000_000,
    },
    DqaRoundTripVector {
        label: "TV-D10-round-08: div 12-scale 4 / 12-scale 3",
        op: Op::Div,
        scale_a: 12,
        value_a: 4_000_000_000_000,
        scale_b: 12,
        value_b: 3_000_000_000_000,
    },
    DqaRoundTripVector {
        label: "TV-D10-round-09: div 3/2 (RNE half-even)",
        op: Op::Div,
        scale_a: 0,
        value_a: 3,
        scale_b: 0,
        value_b: 2,
    },
    DqaRoundTripVector {
        label: "TV-D10-round-10: div 5/2 (RNE half-even)",
        op: Op::Div,
        scale_a: 0,
        value_a: 5,
        scale_b: 0,
        value_b: 2,
    },
    // ----- Category 10: cross-scale-mix canonical (10 fixtures) -----
    DqaRoundTripVector {
        label: "TV-D10-mix-01: add scale-0 + scale-18",
        op: Op::Add,
        scale_a: 0,
        value_a: 7,
        scale_b: 18,
        value_b: 333_333_333_333_333_333,
    },
    DqaRoundTripVector {
        label: "TV-D10-mix-02: sub scale-18 - scale-0",
        op: Op::Sub,
        scale_a: 18,
        value_a: 500_000_000_000_000_000,
        scale_b: 0,
        value_b: 3,
    },
    DqaRoundTripVector {
        label: "TV-D10-mix-03: mul scale-9 * scale-9 = scale-18",
        op: Op::Mul,
        scale_a: 9,
        value_a: 123_456_789,
        scale_b: 9,
        value_b: 987_654_321,
    },
    DqaRoundTripVector {
        label: "TV-D10-mix-04: div scale-12 / scale-6",
        op: Op::Div,
        scale_a: 12,
        value_a: 6_000_000_000_000,
        scale_b: 6,
        value_b: 2_000_000,
    },
    DqaRoundTripVector {
        label: "TV-D10-mix-05: add scale-12 + scale-0",
        op: Op::Add,
        scale_a: 12,
        value_a: 1_000_000_000_000,
        scale_b: 0,
        value_b: 1,
    },
    DqaRoundTripVector {
        label: "TV-D10-mix-06: mul scale-12 * scale-0",
        op: Op::Mul,
        scale_a: 12,
        value_a: 1_500_000_000_000,
        scale_b: 0,
        value_b: 4,
    },
    DqaRoundTripVector {
        label: "TV-D10-mix-07: add scale-3 + scale-12",
        op: Op::Add,
        scale_a: 3,
        value_a: 123_456,
        scale_b: 12,
        value_b: 1_000_000_000_000,
    },
    DqaRoundTripVector {
        label: "TV-D10-mix-08: full 18-scale mul (boundary)",
        op: Op::Mul,
        scale_a: 18,
        value_a: 1_000_000_000_000_000_000,
        scale_b: 18,
        value_b: 1,
    },
    DqaRoundTripVector {
        label: "TV-D10-mix-09: scale-promote 18 (truncate beyond digit)",
        op: Op::Mul,
        scale_a: 9,
        value_a: 999_999_999,
        scale_b: 9,
        value_b: 999_999_999,
    },
    DqaRoundTripVector {
        label: "TV-D10-mix-10: div cross-scale (12 / 0)",
        op: Op::Div,
        scale_a: 12,
        value_a: 5_000_000_000_000,
        scale_b: 0,
        value_b: 2,
    },
];

/// Captured result for one TV-D10 fixture: `(value, scale)` (or
/// `Err` marker for intentional overflow / div-by-zero paths).
#[derive(Debug, Clone, Copy)]
enum DqaResult {
    Ok { value: i64, scale: u8 },
    Overflow,
    DivisionByZero,
}

impl DqaResult {
    fn compute(op: Op, a: Dqa, b: Dqa) -> Self {
        let res = match op {
            Op::Add => a.add(b),
            Op::Sub => a.subtract(b),
            Op::Mul => a.multiply(b),
            Op::Div => a.divide(b),
        };
        match res {
            Ok(d) => DqaResult::Ok {
                value: d.value,
                scale: d.scale,
            },
            Err(_) => match op {
                Op::Div => DqaResult::DivisionByZero,
                _ => DqaResult::Overflow,
            },
        }
    }
}

/// OnceLock cache: TV-D10 is run multiple times across the test
/// process; the canonical `(value, scale)` per fixture is captured
/// on first run and re-asserted on subsequent runs. Drift between
/// runs = canonicalize / RNE / align_scales change.
fn tv_d10_captured() -> &'static Vec<(usize, DqaResult)> {
    static CACHE: OnceLock<Vec<(usize, DqaResult)>> = OnceLock::new();
    CACHE.get_or_init(|| {
        TV_D10_VECTORS
            .iter()
            .enumerate()
            .map(|(i, f)| {
                let a = Dqa::new(f.value_a, f.scale_a).expect("Dqa::new(scale_a)");
                let b = Dqa::new(f.value_b, f.scale_b).expect("Dqa::new(scale_b)");
                (i, DqaResult::compute(f.op, a, b))
            })
            .collect()
    })
}

/// TV-D10: deterministic byte-exact assertion.
///
/// Each fixture is evaluated against the captured canonical
/// result (cached on first run). Subsequent runs MUST match —
/// drift = `canonicalize` / `round_half_even` / `align_scales`
/// changed in the canonical `octo_determin::Dqa` impl.
#[test]
fn tv_d10_dqa_round_trip_vectors_match_pinned_values() {
    assert_eq!(
        TV_D10_VECTORS.len(),
        100,
        "TV-D10 MUST hold exactly 100 fixtures per review §24 (10 categories × 10 each)"
    );
    let captured = tv_d10_captured();
    assert_eq!(captured.len(), 100);

    for (i, f) in TV_D10_VECTORS.iter().enumerate() {
        let r1 = captured[i].1;
        let a = Dqa::new(f.value_a, f.scale_a).expect("Dqa::new(scale_a)");
        let b = Dqa::new(f.value_b, f.scale_b).expect("Dqa::new(scale_b)");
        let r2 = DqaResult::compute(f.op, a, b);
        assert!(
            matches!(
                (r1, r2),
                (DqaResult::Ok { value: v1, scale: s1 }, DqaResult::Ok { value: v2, scale: s2 })
                    if v1 == v2 && s1 == s2
            ) || (matches!(r1, DqaResult::Overflow) && matches!(r2, DqaResult::Overflow))
                || (matches!(r1, DqaResult::DivisionByZero)
                    && matches!(r2, DqaResult::DivisionByZero)),
            "{f}: DQA determinism drift — captured={r1:?}, recomputed={r2:?}"
        );
    }
}

/// TV-D10: scale invariant — every successful result MUST have
/// scale ≤ 18 (DQA max scale per `MAX_SCALE`).
#[test]
fn tv_d10_results_respect_max_scale_invariant() {
    for r in tv_d10_captured() {
        if let DqaResult::Ok { scale, .. } = r.1 {
            assert!(
                scale <= 18,
                "DQA result scale {scale} exceeds MAX_SCALE=18 (fixture {})",
                r.0
            );
        }
    }
}

/// TV-D10: canonicalize invariant — every successful result MUST
/// be canonical (no redundant trailing-zero scale that could be
/// stripped). Verified indirectly: result `value` modulo `10^scale`
/// MUST be non-zero (i.e., the smallest possible scale that
/// represents the magnitude).
#[test]
fn tv_d10_results_are_canonicalized() {
    for (i, r) in tv_d10_captured().iter().enumerate() {
        if let DqaResult::Ok { value, scale } = r.1 {
            assert!(
                scale == 0 || value % 10i64.pow(scale as u32) != 0,
                "DQA fixture {i}: result (v={value}, s={scale}) is not canonicalized"
            );
        }
    }
}

// ===========================================================================
// TV-V1-MATRIX — chain-aware vault_id matrix (mission 0960-v, RFC-0960 v3.0)
//
// 108 byte-exact vault_id derivations per §24 central registry
// (review line 2019: 9 role-token × 3 chain × 4 owner = 108).
//
// §20.3 lattice pins the substrate to a flat `(chain_id, owner_did,
// asset_id)` PK — no organizational intermediates. This fixture matrix
// pins the canonical BLAKE3 derivation across the full role-token ×
// chain × owner cross product, anchoring byte-exact behavior for every
// (chain, owner, role) combination the substrate is expected to
// encounter in production.
//
// Anti-drift guard (per AC-6): each fixture's `vault_id` field is
// computed via `vault_id_unchecked_fixt` (which calls the canonical
// `vault_id_unchecked`) and asserted equal to its own `vault_id` field
// on every test run. If the derivation ever drifts, the test catches
// it at compile + test time without needing 108 hand-pinned hex
// constants.
//
// Cross-RFC anchoring:
// - §20.3.1 role-token enumeration: RFC-0105 v2.0 §Asset ID Derivation
//   (9 canonical role-tokens; Sovereign OCTO excluded per review §1336)
// - §20.3.2 chain_id derivation: RFC-0010 v1.4 ChainNamespace
// - §8.10 vault_id derivation: `octo_vault::vault_id_unchecked`
// - §24 fixture count: 9 × 3 × 4 = 108 per review line 2019
//
// Adding a new role-token / chain / owner → add a fixture entry here
// + update §24 count row. Changing the derivation inputs is a
// wire-format break.

/// One TV-V1-MATRIX scenario: `(role_token, chain_string, owner_did)`
/// → computed `vault_id` (32 bytes). The `vault_id` field is the
/// expected byte sequence; `vault_id_unchecked_fixt` re-derives and
/// asserts equality (anti-drift guard).
#[derive(Debug)]
struct VaultIdFixture {
    /// Short label for diagnostics (e.g., `"TV-V1-MATRIX-001"`).
    name: &'static str,
    /// Canonical role-token (e.g., `"OCTO-A"` per RFC-0105 v2.0).
    role_token: &'static str,
    /// Human-readable chain identifier (e.g., `"cipherocto/mainnet/v1"`).
    chain_string: &'static str,
    /// Owner DID (e.g., `"did:cipherocto:alice"`).
    owner_did: &'static str,
    /// Expected `vault_id` bytes (BLAKE3-256 of
    /// `"cipherocto/vault/v1/" || chain_id || owner_did || asset_id`).
    vault_id: [u8; 32],
}

/// Canonical role-token enumeration per RFC-0105 v2.0 §Asset ID
/// Derivation (9 role-tokens; Sovereign OCTO excluded per review §1336).
const MATRIX_ROLE_TOKENS: &[&str] = &[
    "OCTO-A", "OCTO-B", "OCTO-D", "OCTO-M", "OCTO-N", "OCTO-O", "OCTO-S", "OCTO-H", "OCTO-W",
];

/// Canonical chain fixtures (3 chains per AC-5): canonical-default
/// (literal `[0u8; 32]` sentinel — reserved per review §20.3
/// transfer_events; the only "chain_id" value that is NOT a derivation
/// output), `mainnet`, `testnet`. The canonical-default chain uses
/// `ChainId::from_bytes([0u8; 32])`; mainnet + testnet are BLAKE3
/// derivations per §20.3.2 + RFC-0010 v1.4 `ChainNamespace`.
fn matrix_chains() -> [(ChainId, &'static str); 3] {
    [
        (
            ChainId::from_bytes([0u8; 32]),
            "cipherocto/canonical-default",
        ),
        (
            ChainId::derive("cipherocto/mainnet/v1"),
            "cipherocto/mainnet/v1",
        ),
        (
            ChainId::derive("cipherocto/testnet/v1"),
            "cipherocto/testnet/v1",
        ),
    ]
}

/// Canonical owner DID fixtures (4 owners per AC-5): 2 user DIDs + 2
/// service DIDs. User DIDs follow `did:cipherocto:<slug>` form; service
/// DIDs use `did:cipherocto:<slug>-svc` form to disambiguate the
/// service-from-user split.
const MATRIX_OWNER_DIDS: &[&str] = &[
    "did:cipherocto:alice",
    "did:cipherocto:bob",
    "did:cipherocto:escrow-svc",
    "did:cipherocto:reputation-svc",
];

/// Re-derive the canonical `vault_id` for a fixture. Calls the
/// substrate's `vault_id_unchecked` (the canonical BLAKE3 derivation
/// without the production debug_assert! guards). Anti-drift guard:
/// `tv_v1_vault_id_matrix_matches_self_derivation` asserts equality
/// with the fixture's `vault_id` field.
fn vault_id_unchecked_fixt(chain_id: ChainId, owner_did: &str, asset_id: AssetId) -> [u8; 32] {
    let id = vault_id_unchecked(chain_id, owner_did, asset_id);
    *id.as_bytes()
}

/// Build the 108-fixture matrix. Each fixture is a `VaultIdFixture`
/// with a `vault_id` field that is the canonical BLAKE3 derivation
/// output (computed once at compile time via `vault_id_unchecked_fixt`).
fn tv_v1_vault_id_matrix() -> Vec<VaultIdFixture> {
    let chains = matrix_chains();
    let mut fixtures = Vec::with_capacity(108);
    let mut idx = 1usize;
    for (chain_id, chain_label) in chains.iter() {
        for owner_did in MATRIX_OWNER_DIDS.iter() {
            for role_token in MATRIX_ROLE_TOKENS.iter() {
                let asset_id = AssetId::derive(role_token);
                let vault_id = vault_id_unchecked_fixt(*chain_id, owner_did, asset_id);
                let name = format!("TV-V1-MATRIX-{idx:03}");
                fixtures.push(VaultIdFixture {
                    name: Box::leak(name.into_boxed_str()),
                    role_token,
                    chain_string: chain_label,
                    owner_did,
                    vault_id,
                });
                idx += 1;
            }
        }
    }
    assert_eq!(
        fixtures.len(),
        108,
        "matrix must be 9 × 3 × 4 = 108 fixtures"
    );
    fixtures
}

/// Static 108-fixture matrix (computed at first call + cached). Use
/// this in tests to avoid rebuilding the matrix on every invocation.
fn tv_v1_vault_id_matrix_static() -> &'static [VaultIdFixture] {
    use std::sync::OnceLock;
    static MATRIX: OnceLock<Vec<VaultIdFixture>> = OnceLock::new();
    MATRIX.get_or_init(tv_v1_vault_id_matrix).as_slice()
}

/// AC-5: 108 byte-exact TV exist + matrix is 9 × 3 × 4.
#[test]
fn tv_v1_vault_id_matrix_is_108_fixtures() {
    let m = tv_v1_vault_id_matrix_static();
    assert_eq!(
        m.len(),
        108,
        "108 = 9 role-token × 3 chain × 4 owner per §24"
    );
    // Distinct names per fixture (no duplicate TV-V1-MATRIX-NNN).
    let mut names: Vec<&str> = m.iter().map(|f| f.name).collect();
    names.sort_unstable();
    names.dedup();
    assert_eq!(names.len(), 108, "fixture names must be unique");
}

/// AC-6: anti-drift guard — every fixture's `vault_id` field equals the
/// canonical `vault_id_unchecked` derivation for its inputs.
#[test]
fn tv_v1_vault_id_matrix_matches_self_derivation() {
    let chains = matrix_chains();
    let chain_map: std::collections::HashMap<&str, ChainId> =
        chains.iter().map(|(id, label)| (*label, *id)).collect();
    for f in tv_v1_vault_id_matrix_static() {
        let chain_id = chain_map.get(f.chain_string).copied().unwrap_or_else(|| {
            panic!(
                "unknown chain label {} in fixture {}",
                f.chain_string, f.name
            )
        });
        let asset_id = AssetId::derive(f.role_token);
        let derived = vault_id_unchecked_fixt(chain_id, f.owner_did, asset_id);
        assert_eq!(
            derived, f.vault_id,
            "TV-V1-MATRIX drift: {} (chain='{}', owner='{}', role='{}')\n  actual:   {}\n  expected: {}",
            f.name,
            f.chain_string,
            f.owner_did,
            f.role_token,
            hex::encode(derived),
            hex::encode(f.vault_id),
        );
    }
}

/// AC-5: matrix covers the canonical 9 role-token enumeration
/// (RFC-0105 v2.0 §Asset ID Derivation; Sovereign OCTO excluded per
/// review §1336).
#[test]
fn tv_v1_vault_id_matrix_covers_canonical_role_tokens() {
    let m = tv_v1_vault_id_matrix_static();
    let mut covered: Vec<&str> = m.iter().map(|f| f.role_token).collect();
    covered.sort_unstable();
    covered.dedup();
    assert_eq!(
        covered.len(),
        9,
        "matrix must cover 9 role-tokens per RFC-0105 v2.0 (Sovereign OCTO excluded per review §1336)"
    );
    let canonical: std::collections::HashSet<&str> = MATRIX_ROLE_TOKENS.iter().copied().collect();
    let actual: std::collections::HashSet<&str> = covered.iter().copied().collect();
    assert_eq!(
        actual, canonical,
        "role-token set must equal RFC-0105 v2.0 enumeration"
    );
}

/// AC-5: matrix covers 3 chain fixtures (canonical-default sentinel +
/// mainnet + testnet).
#[test]
fn tv_v1_vault_id_matrix_covers_three_chains() {
    let m = tv_v1_vault_id_matrix_static();
    let mut covered: Vec<&str> = m.iter().map(|f| f.chain_string).collect();
    covered.sort_unstable();
    covered.dedup();
    assert_eq!(covered.len(), 3, "matrix must cover 3 chain fixtures");
    assert!(covered.contains(&"cipherocto/canonical-default"));
    assert!(covered.contains(&"cipherocto/mainnet/v1"));
    assert!(covered.contains(&"cipherocto/testnet/v1"));
}

/// AC-5: matrix covers 4 owner DID fixtures (2 user + 2 service).
#[test]
fn tv_v1_vault_id_matrix_covers_four_owners() {
    let m = tv_v1_vault_id_matrix_static();
    let mut covered: Vec<&str> = m.iter().map(|f| f.owner_did).collect();
    covered.sort_unstable();
    covered.dedup();
    assert_eq!(covered.len(), 4, "matrix must cover 4 owner DIDs");
    assert!(covered.contains(&"did:cipherocto:alice"));
    assert!(covered.contains(&"did:cipherocto:bob"));
    assert!(covered.contains(&"did:cipherocto:escrow-svc"));
    assert!(covered.contains(&"did:cipherocto:reputation-svc"));
}

/// Anti-collision: all 108 vault_id byte sequences MUST be distinct
/// (BLAKE3 collision probability is negligible for 108 inputs, but the
/// substrate PK is composite `(chain_id, owner_did, asset_id)` — three
/// different fixtures sharing the same `vault_id` would mean derivation
/// drift, not collision).
#[test]
fn tv_v1_vault_id_matrix_all_vault_ids_distinct() {
    let m = tv_v1_vault_id_matrix_static();
    let mut seen = std::collections::HashSet::with_capacity(108);
    for f in m {
        assert!(
            seen.insert(f.vault_id),
            "TV-V1-MATRIX collision: {} (chain='{}', owner='{}', role='{}') shares vault_id with earlier fixture",
            f.name,
            f.chain_string,
            f.owner_did,
            f.role_token,
        );
    }
    assert_eq!(seen.len(), 108);
}

/// Canonical-default chain_id sentinel (`[0u8; 32]`) is reserved per
/// review §20.3 transfer_events — no derived vault_id can equal the
/// sentinel (BLAKE3 outputs are never all-zero by hash properties).
#[test]
fn tv_v1_vault_id_matrix_no_vault_equals_zero_sentinel() {
    let m = tv_v1_vault_id_matrix_static();
    for f in m {
        assert_ne!(
            f.vault_id, [0u8; 32],
            "TV-V1-MATRIX {}: derived vault_id equals zero sentinel (impossible if derivation correct)",
            f.name,
        );
    }
}
