//! TV-V1 — byte-exact vault_id derivation vectors.
//!
//! Per review §8.10 + plan §B.3. Each scenario pins (chain_id, owner_did,
//! asset_id) → expected vault_id hex. The fixture loads from
//! `fixtures/tv_v1_vault_id.json` next to this file; vectors are
//! generated by the reference impl (`octo_vault::vault_id`) and pinned
//! here for regression detection.
//!
//! ## Locked derivation contract (changes here are wire-format breaks)
//!
//! ```text
//! vault_id = BLAKE3("cipherocto/vault/v1/" || chain_id || owner_did || asset_id)
//! ```
//!
//! `chain_id = BLAKE3("cipherocto/chain/v1/" || chain_string)` (§20.3.2)
//! `asset_id  = BLAKE3("cipherocto/asset/v1/" || role_token)`     (§20.3.1)
//!
//! Input ordering is fixed (no length-prefixing); each domain-separator
//! prefix is consumed raw. See `octo_vault::vault_id` for the canonical
//! impl + the in-crate derivation test (`vault_id_is_deterministic` +
//! `vault_id_changes_when_any_input_changes`).
//!
//! ## Test vector set
//!
//! 10 scenarios cover:
//! - TV-V1-01..04: deterministic chain / asset variation
//! - TV-V1-05..07: DID form variation (long, short, with slash)
//! - TV-V1-08..10: cross-chain + cross-asset boundary

use octo_vault::{vault_id, AssetId, ChainId};

/// One TV-V1 scenario: inputs (hex-encoded chain/asset IDs + owner_did) →
/// expected `vault_id` hex. Mirrors the §8.10 central-registry format
/// (per plan §8.10 anchoring table).
#[derive(Debug)]
struct VaultIdVector {
    name: &'static str,
    chain_string: &'static str,
    owner_did: &'static str,
    role_token: &'static str,
    expected_vault_id_hex: &'static str,
}

/// TV-V1 reference vectors. Values generated by the reference impl
/// (`octo_vault::vault_id`) on the same Rust toolchain revision that
/// produced this fixture. Changing the BLAKE3 input layout or the prefix
/// domain tag will break this fixture — that is intentional (the
/// derivation is a wire format; byte-exact lock at the central
/// registry).
const TV_V1_VECTORS: &[VaultIdVector] = &[
    VaultIdVector {
        name: "TV-V1-01_did_octo_test_alice_octo_w_testnet",
        chain_string: "cipherocto/testnet/v1",
        owner_did: "did:octo:test-alice",
        role_token: "OCTO_W",
        expected_vault_id_hex: TV_V1_01,
    },
    VaultIdVector {
        name: "TV-V1-02_did_octo_test_bob_octo_w_testnet",
        chain_string: "cipherocto/testnet/v1",
        owner_did: "did:octo:test-bob",
        role_token: "OCTO_W",
        expected_vault_id_hex: TV_V1_02,
    },
    VaultIdVector {
        name: "TV-V1-03_did_octo_test_alice_octo_a_testnet",
        chain_string: "cipherocto/testnet/v1",
        owner_did: "did:octo:test-alice",
        role_token: "OCTO_A",
        expected_vault_id_hex: TV_V1_03,
    },
    VaultIdVector {
        name: "TV-V1-04_did_octo_test_alice_octo_w_mainnet",
        chain_string: "cipherocto/mainnet/v1",
        owner_did: "did:octo:test-alice",
        role_token: "OCTO_W",
        expected_vault_id_hex: TV_V1_04,
    },
    VaultIdVector {
        name: "TV-V1-05_long_did_with_slash_octo_w_testnet",
        chain_string: "cipherocto/testnet/v1",
        owner_did: "did:octo:long-form-identifier-with-many-segments/and/nested/path",
        role_token: "OCTO_W",
        expected_vault_id_hex: TV_V1_05,
    },
    VaultIdVector {
        name: "TV-V1-06_short_did_min_form_octo_w_testnet",
        chain_string: "cipherocto/testnet/v1",
        owner_did: "did:octo:x",
        role_token: "OCTO_W",
        expected_vault_id_hex: TV_V1_06,
    },
    VaultIdVector {
        name: "TV-V1-07_unicode_did_octo_w_testnet",
        chain_string: "cipherocto/testnet/v1",
        owner_did: "did:octo:ß",
        role_token: "OCTO_W",
        expected_vault_id_hex: TV_V1_07,
    },
    VaultIdVector {
        name: "TV-V1-08_empty_owner_did_sentinel",
        chain_string: "cipherocto/testnet/v1",
        owner_did: "",
        role_token: "OCTO_W",
        expected_vault_id_hex: TV_V1_08,
    },
    VaultIdVector {
        name: "TV-V1-09_cross_chain_cross_asset_boundary",
        chain_string: "cipherocto/mainnet/v1",
        owner_did: "did:octo:test-bob",
        role_token: "OCTO_A",
        expected_vault_id_hex: TV_V1_09,
    },
    VaultIdVector {
        name: "TV-V1-10_zero_vault_sentinel_mint",
        chain_string: "",
        owner_did: "",
        role_token: "",
        expected_vault_id_hex: TV_V1_10,
    },
];

/// Hash every known TV-V1 vector and assert it matches the pinned hex.
#[test]
fn tv_v1_vault_id_vectors_match_pinned_hex() {
    for v in TV_V1_VECTORS {
        let chain_id = ChainId::derive(v.chain_string);
        let asset_id = AssetId::derive(v.role_token);
        let id = vault_id(chain_id, v.owner_did, asset_id);
        let actual_hex = hex::encode(id.as_bytes());
        assert_eq!(
            actual_hex, v.expected_vault_id_hex,
            "TV-V1 vector drift: {} (chain='{}', owner='{}', asset='{}')\n  actual:   {}\n  expected: {}",
            v.name, v.chain_string, v.owner_did, v.role_token,
            actual_hex, v.expected_vault_id_hex
        );
    }
}

// ----- Byte-locked expected hex values (generated by reference impl) -----
//
// 32-byte BLAKE3 outputs in lowercase hex, 64 chars per vector. Generated
// 2026-08-16 by `octo_vault::vault_id` over the inputs above. Regenerate
// via `cargo run -p octo-vault --example capture_tv_v1` (see the `examples/`
// dir) — copy from stdout back into the constants below.
//
// These constants ARE the lock. A mismatch between the reference impl and
// the constants here breaks the test — go fix the impl OR fix the inputs,
// never both.

const TV_V1_01: &str = "cf9d419878c8379ce7012fc6b2b249eee8f6d57705c6dada544ee98f194c68f1";
const TV_V1_02: &str = "acd181ab89461f158e866f7927d564c4a7925d1033781a62c39b03cb38a6627e";
const TV_V1_03: &str = "c1469f017522388298d27ce423be9be48cac5a2bc26496be35866d2c3b84ecbe";
const TV_V1_04: &str = "94a23693b0052e44aaaa2c5a0783a018a98150aee16dd6f2abe8a6aa7f3db5cb";
const TV_V1_05: &str = "32cad9fa8929e00c544462b76855eecbf161f31afa59da2185e5ebcc80cb9b4b";
const TV_V1_06: &str = "e547e01c3e601d899dd5921a2d1663f89b36406181c0782f15cc19eeb646917f";
const TV_V1_07: &str = "d4ffce329e31897f5e4a5cc9db1dea8acbac5128a7868fcdae4e00cb051b4d6f";
const TV_V1_08: &str = "dd6442c70e4472a47ab054c37e9fd773ed47e6e321718c2fa5454720a42d60aa";
const TV_V1_09: &str = "6e9ea7e3897887a16003774f9d3918f616ffa499c6d2574eddd8b30791815880";
const TV_V1_10: &str = "de71a9d8e25af74c288e890b029283451634e048b1c7a2f4205075227415f161";
